/** AUTO-GENERATED by scripts/i18n-build-catalog.mjs. */
import { ko as ko_actionPanel } from "../generated/actionPanel.js";
import { ko as ko_app } from "../generated/app.js";
import { ko as ko_appearanceTab } from "../generated/appearanceTab.js";
import { ko as ko_approvalQueueStatus } from "../generated/approvalQueueStatus.js";
import { ko as ko_askUserQuestionCard } from "../generated/askUserQuestionCard.js";
import { ko as ko_assistantCard } from "../generated/assistantCard.js";
import { ko as ko_attachmentChip } from "../generated/attachmentChip.js";
import { ko as ko_auditPanel } from "../generated/auditPanel.js";
import { ko as ko_auditTab } from "../generated/auditTab.js";
import { ko as ko_be_agentList } from "../generated/be_agentList.js";
import { ko as ko_be_agentModeMap } from "../generated/be_agentModeMap.js";
import { ko as ko_be_agentSpawn } from "../generated/be_agentSpawn.js";
import { ko as ko_be_approvalGate } from "../generated/be_approvalGate.js";
import { ko as ko_be_approvalIntent } from "../generated/be_approvalIntent.js";
import { ko as ko_be_askUserQuestion } from "../generated/be_askUserQuestion.js";
import { ko as ko_be_askUserQuestionGate } from "../generated/be_askUserQuestionGate.js";
import { ko as ko_be_bashAstValidator } from "../generated/be_bashAstValidator.js";
import { ko as ko_be_boot } from "../generated/be_boot.js";
import { ko as ko_be_chatDomain } from "../generated/be_chatDomain.js";
import { ko as ko_be_chatStreamState } from "../generated/be_chatStreamState.js";
import { ko as ko_be_conversationLoop } from "../generated/be_conversationLoop.js";
import { ko as ko_be_costEstimator } from "../generated/be_costEstimator.js";
import { ko as ko_be_dlp } from "../generated/be_dlp.js";
import { ko as ko_be_errorClassifier } from "../generated/be_errorClassifier.js";
import { ko as ko_be_executor } from "../generated/be_executor.js";
import { ko as ko_be_hookRunner } from "../generated/be_hookRunner.js";
import { ko as ko_be_knowledgeCap } from "../generated/be_knowledgeCap.js";
import { ko as ko_be_knowledgeSearch } from "../generated/be_knowledgeSearch.js";
import { ko as ko_be_main } from "../generated/be_main.js";
import { ko as ko_be_mcpClient } from "../generated/be_mcpClient.js";
import { ko as ko_be_mcpGovernance } from "../generated/be_mcpGovernance.js";
import { ko as ko_be_mcpManager } from "../generated/be_mcpManager.js";
import { ko as ko_be_memoryManager } from "../generated/be_memoryManager.js";
import { ko as ko_be_permissionManager } from "../generated/be_permissionManager.js";
import { ko as ko_be_permissionModeApply } from "../generated/be_permissionModeApply.js";
import { ko as ko_be_pluginExpansion } from "../generated/be_pluginExpansion.js";
import { ko as ko_be_pluginRuntime } from "../generated/be_pluginRuntime.js";
import { ko as ko_be_pluginUiHost } from "../generated/be_pluginUiHost.js";
import { ko as ko_be_policyStore } from "../generated/be_policyStore.js";
import { ko as ko_be_postTurnHookChain } from "../generated/be_postTurnHookChain.js";
import { ko as ko_be_preferenceRefreshService } from "../generated/be_preferenceRefreshService.js";
import { ko as ko_be_preload } from "../generated/be_preload.js";
import { ko as ko_be_pythonRuntime } from "../generated/be_pythonRuntime.js";
import { ko as ko_be_renderHtml } from "../generated/be_renderHtml.js";
import { ko as ko_be_renderHtmlPreview } from "../generated/be_renderHtmlPreview.js";
import { ko as ko_be_rolePresets } from "../generated/be_rolePresets.js";
import { ko as ko_be_routineEngine } from "../generated/be_routineEngine.js";
import { ko as ko_be_routineSchedule } from "../generated/be_routineSchedule.js";
import { ko as ko_be_runtimeIndex } from "../generated/be_runtimeIndex.js";
import { ko as ko_be_sandboxCapability } from "../generated/be_sandboxCapability.js";
import { ko as ko_be_shellPathPolicy } from "../generated/be_shellPathPolicy.js";
import { ko as ko_be_shutdownRoutines } from "../generated/be_shutdownRoutines.js";
import { ko as ko_be_skillList } from "../generated/be_skillList.js";
import { ko as ko_be_skillLoad } from "../generated/be_skillLoad.js";
import { ko as ko_be_streamCollector } from "../generated/be_streamCollector.js";
import { ko as ko_be_structuredCompact } from "../generated/be_structuredCompact.js";
import { ko as ko_be_subagentRunner } from "../generated/be_subagentRunner.js";
import { ko as ko_be_systemPromptBuilder } from "../generated/be_systemPromptBuilder.js";
import { ko as ko_be_todoSessionWrite } from "../generated/be_todoSessionWrite.js";
import { ko as ko_be_toolSearch } from "../generated/be_toolSearch.js";
import { ko as ko_be_tools } from "../generated/be_tools.js";
import { ko as ko_be_whitelistBootstrap } from "../generated/be_whitelistBootstrap.js";
import { ko as ko_be_windowDomain } from "../generated/be_windowDomain.js";
import { ko as ko_be_windowTitlebarShell } from "../generated/be_windowTitlebarShell.js";
import { ko as ko_bootstrapStatusBanner } from "../generated/bootstrapStatusBanner.js";
import { ko as ko_bottomActionRow } from "../generated/bottomActionRow.js";
import { ko as ko_catppuccinLatte } from "../generated/catppuccinLatte.js";
import { ko as ko_catppuccinMocha } from "../generated/catppuccinMocha.js";
import { ko as ko_chatPreviewRail } from "../generated/chatPreviewRail.js";
import { ko as ko_chatTab } from "../generated/chatTab.js";
import { ko as ko_chatView } from "../generated/chatView.js";
import { ko as ko_checkpointDivider } from "../generated/checkpointDivider.js";
import { ko as ko_cherryBlossom } from "../generated/cherryBlossom.js";
import { ko as ko_clipboardPaste } from "../generated/clipboardPaste.js";
import { ko as ko_commandActions } from "../generated/commandActions.js";
import { ko as ko_commandPopover } from "../generated/commandPopover.js";
import { ko as ko_commandPopoverPanel } from "../generated/commandPopoverPanel.js";
import { ko as ko_compactedToolResult } from "../generated/compactedToolResult.js";
import { ko as ko_composer } from "../generated/composer.js";
import { ko as ko_composerPlaceholder } from "../generated/composerPlaceholder.js";
import { ko as ko_composerProjectSelector } from "../generated/composerProjectSelector.js";
import { ko as ko_constants } from "../generated/constants.js";
import { ko as ko_customTitleBar } from "../generated/customTitleBar.js";
import { ko as ko_defaultTourScenarios } from "../generated/defaultTourScenarios.js";
import { ko as ko_deferredApprovalChip } from "../generated/deferredApprovalChip.js";
import { ko as ko_deferredQueueDialog } from "../generated/deferredQueueDialog.js";
import { ko as ko_deferredQueuePanel } from "../generated/deferredQueuePanel.js";
import { ko as ko_detachedView } from "../generated/detachedView.js";
import { ko as ko_devToolsPanel } from "../generated/devToolsPanel.js";
import { ko as ko_errorBoundary } from "../generated/errorBoundary.js";
import { ko as ko_executiveGraphite } from "../generated/executiveGraphite.js";
import { ko as ko_fileEditDiff } from "../generated/fileEditDiff.js";
import { ko as ko_firstTaskProposals } from "../generated/firstTaskProposals.js";
import { ko as ko_forest } from "../generated/forest.js";
import { ko as ko_formatIpcError } from "../generated/formatIpcError.js";
import { ko as ko_generalTab } from "../generated/generalTab.js";
import { ko as ko_gruvboxDarkHard } from "../generated/gruvboxDarkHard.js";
import { ko as ko_highContrast } from "../generated/highContrast.js";
import { ko as ko_history } from "../generated/history.js";
import { ko as ko_htmlPreview } from "../generated/htmlPreview.js";
import { ko as ko_inputActionBar } from "../generated/inputActionBar.js";
import { ko as ko_lazyCalendar } from "../generated/lazyCalendar.js";
import { ko as ko_llmTab } from "../generated/llmTab.js";
import { ko as ko_mainToolbar } from "../generated/mainToolbar.js";
import { ko as ko_marketplaceAnnouncementBanner } from "../generated/marketplaceAnnouncementBanner.js";
import { ko as ko_marketplaceTab } from "../generated/marketplaceTab.js";
import { ko as ko_marketplaceUpdateBanner } from "../generated/marketplaceUpdateBanner.js";
import { ko as ko_mcpAppPipPanel } from "../generated/mcpAppPipPanel.js";
import { ko as ko_mcpAppView } from "../generated/mcpAppView.js";
import { ko as ko_mcpTab } from "../generated/mcpTab.js";
import { ko as ko_memorySearchPanel } from "../generated/memorySearchPanel.js";
import { ko as ko_memorySeedDialog } from "../generated/memorySeedDialog.js";
import { ko as ko_messageQueuePanel } from "../generated/messageQueuePanel.js";
import { ko as ko_messageQueueStore } from "../generated/messageQueueStore.js";
import { ko as ko_midnight } from "../generated/midnight.js";
import { ko as ko_nord } from "../generated/nord.js";
import { ko as ko_outOfAllowedDirCard } from "../generated/outOfAllowedDirCard.js";
import { ko as ko_overlayCard } from "../generated/overlayCard.js";
import { ko as ko_overlayCardRegion } from "../generated/overlayCardRegion.js";
import { ko as ko_permissionDecisionCard } from "../generated/permissionDecisionCard.js";
import { ko as ko_permissionEvaluationContextPanel } from "../generated/permissionEvaluationContextPanel.js";
import { ko as ko_permissionModeBadge } from "../generated/permissionModeBadge.js";
import { ko as ko_permissionReviewStatusCard } from "../generated/permissionReviewStatusCard.js";
import { ko as ko_permissionsTab } from "../generated/permissionsTab.js";
import { ko as ko_personalizedWelcome } from "../generated/personalizedWelcome.js";
import { ko as ko_pluginAuthSection } from "../generated/pluginAuthSection.js";
import { ko as ko_pluginConfigSchemaForm } from "../generated/pluginConfigSchemaForm.js";
import { ko as ko_pluginConfigTab } from "../generated/pluginConfigTab.js";
import { ko as ko_pluginGridButton } from "../generated/pluginGridButton.js";
import { ko as ko_pluginInstallDialog } from "../generated/pluginInstallDialog.js";
import { ko as ko_pluginPerfTab } from "../generated/pluginPerfTab.js";
import { ko as ko_pluginRecommendationMatrix } from "../generated/pluginRecommendationMatrix.js";
import { ko as ko_pluginShowcase } from "../generated/pluginShowcase.js";
import { ko as ko_pluginUninstallDialog } from "../generated/pluginUninstallDialog.js";
import { ko as ko_postTourFirstTask } from "../generated/postTourFirstTask.js";
import { ko as ko_privacyTab } from "../generated/privacyTab.js";
import { ko as ko_reasoningCard } from "../generated/reasoningCard.js";
import { ko as ko_remoteA2aActionButton } from "../generated/remoteA2aActionButton.js";
import { ko as ko_rolesTab } from "../generated/rolesTab.js";
import { ko as ko_rosePine } from "../generated/rosePine.js";
import { ko as ko_routinePanel } from "../generated/routinePanel.js";
import { ko as ko_savedToast } from "../generated/savedToast.js";
import { ko as ko_scenarioShowcase } from "../generated/scenarioShowcase.js";
import { ko as ko_sessionResumeDivider } from "../generated/sessionResumeDivider.js";
import { ko as ko_sessionTodoPanel } from "../generated/sessionTodoPanel.js";
import { ko as ko_settingsContent } from "../generated/settingsContent.js";
import { ko as ko_settingsWindow } from "../generated/settingsWindow.js";
import { ko as ko_sidebar } from "../generated/sidebar.js";
import { ko as ko_skillBadge } from "../generated/skillBadge.js";
import { ko as ko_slashPicker } from "../generated/slashPicker.js";
import { ko as ko_solarizedLight } from "../generated/solarizedLight.js";
import { ko as ko_sparkline } from "../generated/sparkline.js";
import { ko as ko_spotlightTour } from "../generated/spotlightTour.js";
import { ko as ko_starredView } from "../generated/starredView.js";
import { ko as ko_statusBar } from "../generated/statusBar.js";
import { ko as ko_subAgentCard } from "../generated/subAgentCard.js";
import { ko as ko_suggestedRepliesChipRow } from "../generated/suggestedRepliesChipRow.js";
import { ko as ko_suggestedRepliesGhost } from "../generated/suggestedRepliesGhost.js";
import { ko as ko_summaryToast } from "../generated/summaryToast.js";
import { ko as ko_tokenCostBadge } from "../generated/tokenCostBadge.js";
import { ko as ko_tokenProgressRing } from "../generated/tokenProgressRing.js";
import { ko as ko_tokyoNight } from "../generated/tokyoNight.js";
import { ko as ko_toolApprovalDialog } from "../generated/toolApprovalDialog.js";
import { ko as ko_toolDisplay } from "../generated/toolDisplay.js";
import { ko as ko_toolGroupCard } from "../generated/toolGroupCard.js";
import { ko as ko_trustOriginLabel } from "../generated/trustOriginLabel.js";
import { ko as ko_turnActionBar } from "../generated/turnActionBar.js";
import { ko as ko_unifiedSearchPanel } from "../generated/unifiedSearchPanel.js";
import { ko as ko_usageDashboard } from "../generated/usageDashboard.js";
import { ko as ko_useChatState } from "../generated/useChatState.js";
import { ko as ko_useMemorySearch } from "../generated/useMemorySearch.js";
import { ko as ko_usePluginMarketplace } from "../generated/usePluginMarketplace.js";
import { ko as ko_useSettingsOrchestration } from "../generated/useSettingsOrchestration.js";
import { ko as ko_useStarred } from "../generated/useStarred.js";
import { ko as ko_useStatusBarInstall } from "../generated/useStatusBarInstall.js";
import { ko as ko_useStatusBarVendor } from "../generated/useStatusBarVendor.js";
import { ko as ko_userMessageEditor } from "../generated/userMessageEditor.js";
import { ko as ko_viewModeBanner } from "../generated/viewModeBanner.js";
import { ko as ko_violetDark } from "../generated/violetDark.js";
import { ko as ko_violetLight } from "../generated/violetLight.js";
import { ko as ko_webTab } from "../generated/webTab.js";
import { ko as ko_workBoard } from "../generated/workBoard.js";
import { ko as ko_workGroup } from "../generated/workGroup.js";

export const koMessages: Record<string, string> = {
  ...ko_actionPanel,
  ...ko_app,
  ...ko_appearanceTab,
  ...ko_approvalQueueStatus,
  ...ko_askUserQuestionCard,
  ...ko_assistantCard,
  ...ko_attachmentChip,
  ...ko_auditPanel,
  ...ko_auditTab,
  ...ko_be_agentList,
  ...ko_be_agentModeMap,
  ...ko_be_agentSpawn,
  ...ko_be_approvalGate,
  ...ko_be_approvalIntent,
  ...ko_be_askUserQuestion,
  ...ko_be_askUserQuestionGate,
  ...ko_be_bashAstValidator,
  ...ko_be_boot,
  ...ko_be_chatDomain,
  ...ko_be_chatStreamState,
  ...ko_be_conversationLoop,
  ...ko_be_costEstimator,
  ...ko_be_dlp,
  ...ko_be_errorClassifier,
  ...ko_be_executor,
  ...ko_be_hookRunner,
  ...ko_be_knowledgeCap,
  ...ko_be_knowledgeSearch,
  ...ko_be_main,
  ...ko_be_mcpClient,
  ...ko_be_mcpGovernance,
  ...ko_be_mcpManager,
  ...ko_be_memoryManager,
  ...ko_be_permissionManager,
  ...ko_be_permissionModeApply,
  ...ko_be_pluginExpansion,
  ...ko_be_pluginRuntime,
  ...ko_be_pluginUiHost,
  ...ko_be_policyStore,
  ...ko_be_postTurnHookChain,
  ...ko_be_preferenceRefreshService,
  ...ko_be_preload,
  ...ko_be_pythonRuntime,
  ...ko_be_renderHtml,
  ...ko_be_renderHtmlPreview,
  ...ko_be_rolePresets,
  ...ko_be_routineEngine,
  ...ko_be_routineSchedule,
  ...ko_be_runtimeIndex,
  ...ko_be_sandboxCapability,
  ...ko_be_shellPathPolicy,
  ...ko_be_shutdownRoutines,
  ...ko_be_skillList,
  ...ko_be_skillLoad,
  ...ko_be_streamCollector,
  ...ko_be_structuredCompact,
  ...ko_be_subagentRunner,
  ...ko_be_systemPromptBuilder,
  ...ko_be_todoSessionWrite,
  ...ko_be_toolSearch,
  ...ko_be_tools,
  ...ko_be_whitelistBootstrap,
  ...ko_be_windowDomain,
  ...ko_be_windowTitlebarShell,
  ...ko_bootstrapStatusBanner,
  ...ko_bottomActionRow,
  ...ko_catppuccinLatte,
  ...ko_catppuccinMocha,
  ...ko_chatPreviewRail,
  ...ko_chatTab,
  ...ko_chatView,
  ...ko_checkpointDivider,
  ...ko_cherryBlossom,
  ...ko_clipboardPaste,
  ...ko_commandActions,
  ...ko_commandPopover,
  ...ko_commandPopoverPanel,
  ...ko_compactedToolResult,
  ...ko_composer,
  ...ko_composerPlaceholder,
  ...ko_composerProjectSelector,
  ...ko_constants,
  ...ko_customTitleBar,
  ...ko_defaultTourScenarios,
  ...ko_deferredApprovalChip,
  ...ko_deferredQueueDialog,
  ...ko_deferredQueuePanel,
  ...ko_detachedView,
  ...ko_devToolsPanel,
  ...ko_errorBoundary,
  ...ko_executiveGraphite,
  ...ko_fileEditDiff,
  ...ko_firstTaskProposals,
  ...ko_forest,
  ...ko_formatIpcError,
  ...ko_generalTab,
  ...ko_gruvboxDarkHard,
  ...ko_highContrast,
  ...ko_history,
  ...ko_htmlPreview,
  ...ko_inputActionBar,
  ...ko_lazyCalendar,
  ...ko_llmTab,
  ...ko_mainToolbar,
  ...ko_marketplaceAnnouncementBanner,
  ...ko_marketplaceTab,
  ...ko_marketplaceUpdateBanner,
  ...ko_mcpAppPipPanel,
  ...ko_mcpAppView,
  ...ko_mcpTab,
  ...ko_memorySearchPanel,
  ...ko_memorySeedDialog,
  ...ko_messageQueuePanel,
  ...ko_messageQueueStore,
  ...ko_midnight,
  ...ko_nord,
  ...ko_outOfAllowedDirCard,
  ...ko_overlayCard,
  ...ko_overlayCardRegion,
  ...ko_permissionDecisionCard,
  ...ko_permissionEvaluationContextPanel,
  ...ko_permissionModeBadge,
  ...ko_permissionReviewStatusCard,
  ...ko_permissionsTab,
  ...ko_personalizedWelcome,
  ...ko_pluginAuthSection,
  ...ko_pluginConfigSchemaForm,
  ...ko_pluginConfigTab,
  ...ko_pluginGridButton,
  ...ko_pluginInstallDialog,
  ...ko_pluginPerfTab,
  ...ko_pluginRecommendationMatrix,
  ...ko_pluginShowcase,
  ...ko_pluginUninstallDialog,
  ...ko_postTourFirstTask,
  ...ko_privacyTab,
  ...ko_reasoningCard,
  ...ko_remoteA2aActionButton,
  ...ko_rolesTab,
  ...ko_rosePine,
  ...ko_routinePanel,
  ...ko_savedToast,
  ...ko_scenarioShowcase,
  ...ko_sessionResumeDivider,
  ...ko_sessionTodoPanel,
  ...ko_settingsContent,
  ...ko_settingsWindow,
  ...ko_sidebar,
  ...ko_skillBadge,
  ...ko_slashPicker,
  ...ko_solarizedLight,
  ...ko_sparkline,
  ...ko_spotlightTour,
  ...ko_starredView,
  ...ko_statusBar,
  ...ko_subAgentCard,
  ...ko_suggestedRepliesChipRow,
  ...ko_suggestedRepliesGhost,
  ...ko_summaryToast,
  ...ko_tokenCostBadge,
  ...ko_tokenProgressRing,
  ...ko_tokyoNight,
  ...ko_toolApprovalDialog,
  ...ko_toolDisplay,
  ...ko_toolGroupCard,
  ...ko_trustOriginLabel,
  ...ko_turnActionBar,
  ...ko_unifiedSearchPanel,
  ...ko_usageDashboard,
  ...ko_useChatState,
  ...ko_useMemorySearch,
  ...ko_usePluginMarketplace,
  ...ko_useSettingsOrchestration,
  ...ko_useStarred,
  ...ko_useStatusBarInstall,
  ...ko_useStatusBarVendor,
  ...ko_userMessageEditor,
  ...ko_viewModeBanner,
  ...ko_violetDark,
  ...ko_violetLight,
  ...ko_webTab,
  ...ko_workBoard,
  ...ko_workGroup,
};
