/**
 * Composer attachment domain IPC handlers.
 * Covers: lvis:attach:openFile, lvis:attach:readImage,
 *         lvis:attach:saveClipboardImage, lvis:attach:discardClipboardImage,
 *         lvis:attach:openExternal
 *
 * Renderer reaches these via window.lvis.attach.* (see preload.ts).
 */
import { dialog, ipcMain, nativeImage, shell } from "electron";
import { t } from "../../i18n/index.js";
import { promises as fs } from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { validateHostRendererSender, auditUnauthorized } from "../gated.js";
import { CHANNELS } from "../../contract/app-contract.js";
import type { IpcDeps } from "../types.js";
import { DENY_EXTENSIONS as DENY_LIST } from "../../shared/attachments-deny-list.js";
import {
  MAX_COMPOSER_IMAGE_BYTES,
  sniffComposerImageFormat,
} from "../../shared/composer-image-input.js";

// Convert the shared array into a Set once at module load for O(1) lookup
// in the file-picker hot path. Source of truth lives in the shared module.
const DENY_EXTENSIONS = new Set<string>(DENY_LIST);

/**
 * Session-scoped allowlist of paths the user has explicitly authorized
 * (via the OS file picker or clipboard paste). `readImage` and
 * `openExternal` MUST consult this set before touching the filesystem
 * — otherwise a compromised renderer could pass an arbitrary path
 * (`/Users/.../secrets.json` symlinked to `*.png`) and exfiltrate
 * its contents via the returned dataURL, or launch an attacker-planted
 * binary via shell.openPath.
 *
 * Module-scope, app-lifetime — there is no security benefit to clearing
 * across navigations, and re-prompting the user every chat would be
 * hostile UX. The threat model only requires that paths are
 * user-acknowledged at LEAST ONCE in this app run.
 *
 * Bounded by {@link ATTACH_ALLOWLIST_MAX} with insertion-order LRU
 * eviction (Set iteration order = insertion order; oldest evicted first).
 * Prevents unbounded memory growth in long-lived sessions where a power
 * user might attach thousands of files. Eviction risk is benign — if the
 * user re-attaches a previously evicted path, the OS picker re-authorizes
 * it. The cap is high enough (10k) that normal usage never trips it.
 */
const ATTACH_ALLOWLIST_MAX = 10_000;
const ATTACH_PATH_ALLOWLIST = new Set<string>();
// Only paths generated by this process enter this set. A late renderer refusal
// may revoke their capabilities, but never pathname-delete them: Node exposes
// no cross-platform compare-and-unlink primitive, so a replacement race would
// otherwise risk unlinking a user-managed file.
const CLIPBOARD_TEMP_IMAGE_PATHS = new Set<string>();

function authorizePath(p: string): void {
  // Re-add to move existing entries to the tail (Set iteration is
  // insertion-order, so deleting + re-adding refreshes recency).
  if (ATTACH_PATH_ALLOWLIST.has(p)) ATTACH_PATH_ALLOWLIST.delete(p);
  ATTACH_PATH_ALLOWLIST.add(p);
  while (ATTACH_PATH_ALLOWLIST.size > ATTACH_ALLOWLIST_MAX) {
    const oldest = ATTACH_PATH_ALLOWLIST.values().next().value;
    if (oldest === undefined) break;
    ATTACH_PATH_ALLOWLIST.delete(oldest);
    CLIPBOARD_TEMP_IMAGE_PATHS.delete(oldest);
  }
}

function authorizeClipboardTempImage(
  filePath: string,
): void {
  authorizePath(filePath);
  CLIPBOARD_TEMP_IMAGE_PATHS.add(filePath);
}

/**
 * Preserve the old permissive pre-decode DoS guard. The decoded image cap
 * itself comes from the shared composer image input contract.
 */
const MAX_CLIPBOARD_BASE64_INPUT_CHARS = MAX_COMPOSER_IMAGE_BYTES * 2;

function getExt(p: string): string {
  const i = p.lastIndexOf(".");
  return i >= 0 ? p.slice(i + 1).toLowerCase() : "";
}

/**
 * Reads only the bytes needed by the shared magic sniffer. Picker metadata
 * must reflect file content, but generic files must never be buffered merely
 * to decide whether they are images.
 */
async function sniffImageFilePrefix(filePath: string) {
  const handle = await fs.open(filePath, "r");
  try {
    const prefix = Buffer.alloc(12);
    const { bytesRead } = await handle.read(prefix, 0, prefix.length, 0);
    return sniffComposerImageFormat(prefix.subarray(0, bytesRead));
  } finally {
    await handle.close();
  }
}


export interface OpenFileResult {
  canceled: boolean;
  files: Array<{
    path: string;
    name: string;
    ext: string;
    bytes: number;
    isImage: boolean;
    mimeType?: string;
  }>;
  rejected: string[]; // paths rejected by deny-list
}

export interface ReadImageResult {
  ok: boolean;
  dataUrl?: string;
  mimeType?: string;
  width?: number;
  height?: number;
  bytes?: number;
  error?: string;
}

export interface SaveClipboardImageInput {
  /**
   * Base64-encoded image bytes (no `data:` prefix). Format is autodetected
   * from the leading magic bytes — PNG / JPEG / GIF / WebP / BMP all
   * supported. Renderer does not need to negotiate the format up front.
   */
  base64: string;
}

export interface SaveClipboardImageResult {
  ok: boolean;
  path?: string;
  width?: number;
  height?: number;
  bytes?: number;
  mimeType?: string;
  dataUrl?: string;
  error?: string;
}

/** Result of revoking an unadopted app-owned clipboard image capability. */
export interface DiscardClipboardImageResult {
  ok: boolean;
  /** Kept on disk for OS temp cleanup rather than risking pathname-delete races. */
  retained?: true;
  error?: "unauthorized" | "clipboard-image-not-owned";
}

export function registerAttachHandlers(deps: IpcDeps): void {
  const { auditLogger, getMainWindow } = deps;

  ipcMain.handle(CHANNELS.attach.openFile, async (e): Promise<OpenFileResult> => {
    if (!validateHostRendererSender(e)) {
      auditUnauthorized(auditLogger, CHANNELS.attach.openFile, e);
      return { canceled: true, files: [], rejected: [] };
    }
    const win = getMainWindow();
    if (!win) return { canceled: true, files: [], rejected: [] };

    const result = await dialog.showOpenDialog(win, {
      title: t("mainDialog.attachTitle"),
      properties: ["openFile", "multiSelections"],
    });
    if (result.canceled || result.filePaths.length === 0) {
      return { canceled: true, files: [], rejected: [] };
    }

    const files: OpenFileResult["files"] = [];
    const rejected: string[] = [];
    for (const p of result.filePaths) {
      const ext = getExt(p);
      if (DENY_EXTENSIONS.has(ext)) {
        rejected.push(p);
        continue;
      }
      try {
        const stat = await fs.stat(p);
        const imageFormat = await sniffImageFilePrefix(p);
        const isImage = imageFormat !== null && imageFormat !== undefined;
        files.push({
          path: p,
          name: path.basename(p),
          ext,
          bytes: stat.size,
          isImage,
          mimeType: imageFormat?.mimeType,
        });
        // Authorize this exact path for downstream readImage / openExternal.
        // The user just acknowledged it via the OS picker, so subsequent
        // reads are no longer blind-trusting renderer-supplied paths.
        authorizePath(p);
      } catch {
        rejected.push(p);
      }
    }
    return { canceled: false, files, rejected };
  });

  ipcMain.handle(
    CHANNELS.attach.readImage,
    async (e, filePath: string): Promise<ReadImageResult> => {
      if (!validateHostRendererSender(e)) {
        auditUnauthorized(auditLogger, CHANNELS.attach.readImage, e);
        return { ok: false, error: "unauthorized" };
      }
      try {
        // Path-allowlist gate: the renderer can ask to read any string,
        // so we MUST verify the path was previously authorized via the
        // OS file picker. Without this gate, a compromised renderer
        // (XSS in a plugin webview, malicious paste-bridge, etc.) could
        // exfiltrate arbitrary files by symlinking them to a `.png`
        // and calling readImage(arbitrary_path).
        if (!ATTACH_PATH_ALLOWLIST.has(filePath)) {
          return { ok: false, error: "path_not_authorized" };
        }
        // Stat first so we can refuse to buffer a multi-GB file. Vision
        // APIs reject anything beyond ~20MB, so 25MB cap is generous.
        const stat = await fs.stat(filePath);
        if (stat.size > MAX_COMPOSER_IMAGE_BYTES) {
          return {
            ok: false,
            error: `image_too_large: ${stat.size} > ${MAX_COMPOSER_IMAGE_BYTES}`,
          };
        }
        if (!await sniffImageFilePrefix(filePath)) {
          return { ok: false, error: "not_image" };
        }
        const buf = await fs.readFile(filePath);
        if (buf.length > MAX_COMPOSER_IMAGE_BYTES) {
          return {
            ok: false,
            error: `image_too_large: ${buf.length} > ${MAX_COMPOSER_IMAGE_BYTES}`,
          };
        }
        // Re-sniff after the full read so a file replacement race cannot make
        // a claimed image MIME disagree with the bytes sent to a provider.
        const imageFormat = sniffComposerImageFormat(buf);
        if (!imageFormat) {
          return { ok: false, error: "not_image" };
        }
        const mimeType = imageFormat.mimeType;
        const img = nativeImage.createFromBuffer(buf);
        const { width, height } = img.getSize();
        const dataUrl = `data:${mimeType};base64,${buf.toString("base64")}`;
        return {
          ok: true,
          dataUrl,
          mimeType,
          width,
          height,
          bytes: buf.length,
        };
      } catch (err) {
        return {
          ok: false,
          error: err instanceof Error ? err.message : String(err),
        };
      }
    },
  );

  ipcMain.handle(
    CHANNELS.attach.saveClipboardImage,
    async (e, input: SaveClipboardImageInput): Promise<SaveClipboardImageResult> => {
      if (!validateHostRendererSender(e)) {
        auditUnauthorized(auditLogger, CHANNELS.attach.saveClipboardImage, e);
        return { ok: false, error: "unauthorized" };
      }
      try {
        // Cap base64 size before decoding. Without this, a compromised
        // renderer can flood `os.tmpdir()` with multi-GB writes and/or
        // trigger native image-decoder vulnerabilities (e.g. WebP libwebp
        // CVE class) on attacker-shaped buffers in the main process.
        if (typeof input?.base64 !== "string") {
          return { ok: false, error: "invalid_payload" };
        }
        if (input.base64.length > MAX_CLIPBOARD_BASE64_INPUT_CHARS) {
          // base64 is ~4/3 the binary size, *2 is a generous bound that
          // still rejects pathological multi-GB strings before Buffer.from.
          return {
            ok: false,
            error: `clipboard_too_large: ${input.base64.length} > ${MAX_CLIPBOARD_BASE64_INPUT_CHARS}`,
          };
        }
        const buf = Buffer.from(input.base64, "base64");
        if (buf.length > MAX_COMPOSER_IMAGE_BYTES) {
          return {
            ok: false,
            error: `clipboard_too_large: ${buf.length} > ${MAX_COMPOSER_IMAGE_BYTES}`,
          };
        }
        // Clipboard content has no trusted extension. The same strict magic
        // contract used by subscription input keeps a false image MIME from
        // reaching a provider or the app-owned temp directory.
        const detected = sniffComposerImageFormat(buf);
        if (!detected) {
          return { ok: false, error: "not_image" };
        }
        // Buffer accepts whitespace and other permissive base64 spellings.
        // Return one canonical spelling that downstream validators accept.
        const canonicalBase64 = buf.toString("base64");
        const img = nativeImage.createFromBuffer(buf);
        const { width, height } = img.getSize();
        // A fresh private directory is the secure boundary. A random basename
        // in the shared OS temp directory still lets an attacker race the path
        // before creation; mkdtemp reserves the directory atomically.
        const targetDir = await fs.mkdtemp(path.join(os.tmpdir(), "lvis-clip-"));
        const target = path.join(targetDir, "image." + detected.extension);
        // wx binds the capability to the exact file this process created.
        await fs.writeFile(target, buf, { flag: "wx", mode: 0o600 });
        // Authorize for downstream readImage / openExternal — we just
        // wrote this file ourselves so it's safe to read back.
        authorizeClipboardTempImage(target);
        const dataUrl = `data:${detected.mimeType};base64,${canonicalBase64}`;
        return {
          ok: true,
          path: target,
          width,
          height,
          bytes: buf.length,
          mimeType: detected.mimeType,
          dataUrl,
        };
      } catch (err) {
        return {
          ok: false,
          error: err instanceof Error ? err.message : String(err),
        };
      }
    },
  );

  ipcMain.handle(
    CHANNELS.attach.discardClipboardImage,
    async (e, filePath: unknown): Promise<DiscardClipboardImageResult> => {
      if (!validateHostRendererSender(e)) {
        auditUnauthorized(auditLogger, CHANNELS.attach.discardClipboardImage, e);
        return { ok: false, error: "unauthorized" };
      }
      if (typeof filePath !== "string") {
        return { ok: false, error: "clipboard-image-not-owned" };
      }
      if (!CLIPBOARD_TEMP_IMAGE_PATHS.has(filePath)) {
        return { ok: false, error: "clipboard-image-not-owned" };
      }

      // Do not lstat+unlink here. A pathname may be replaced after an identity
      // check and before unlink; Node has no cross-platform compare-and-unlink
      // operation. Revocation is safe, while the app-created temp file can be
      // collected by the operating system without touching user files.
      ATTACH_PATH_ALLOWLIST.delete(filePath);
      CLIPBOARD_TEMP_IMAGE_PATHS.delete(filePath);
      return { ok: true, retained: true };
    },
  );
  ipcMain.handle(
    CHANNELS.attach.openExternal,
    async (e, filePath: string): Promise<{ ok: boolean; error?: string }> => {
      if (!validateHostRendererSender(e)) {
        auditUnauthorized(auditLogger, CHANNELS.attach.openExternal, e);
        return { ok: false, error: "unauthorized" };
      }
      try {
        // Same allowlist gate as readImage. Without it, a compromised
        // renderer could trigger `shell.openPath("/path/to/malicious.app")`
        // and execute attacker-planted binaries. Re-applying the
        // deny-list also blocks dangerous extensions even if the path
        // somehow ends up in the allowlist via a future bug.
        if (!ATTACH_PATH_ALLOWLIST.has(filePath)) {
          return { ok: false, error: "path_not_authorized" };
        }
        if (DENY_EXTENSIONS.has(getExt(filePath))) {
          return { ok: false, error: "denied_extension" };
        }
        const result = await shell.openPath(filePath);
        if (result) return { ok: false, error: result };
        return { ok: true };
      } catch (err) {
        return {
          ok: false,
          error: err instanceof Error ? err.message : String(err),
        };
      }
    },
  );
}
