/**
 * http-server.ts — #1436 loopback HTTP transport for the local API (#1409
 * follow-up).
 *
 * Exposes the transport-agnostic {@link LocalApi} dispatcher over a
 * node:http server bound to loopback ONLY. This is the network edge for the
 * external surface: it never constructs services, it forwards validated
 * requests to the injected dispatcher, and it is fail-closed on every axis.
 *
 * SECURITY:
 *   - Bind host hard-defaults to 127.0.0.1 and MUST never default to 0.0.0.0 —
 *     the server is reachable only from the local machine.
 *   - EVERY route (health included) requires `Authorization: Bearer <secret>`
 *     with a constant-time compare. Missing/invalid → 401 before any other
 *     processing. The secret and the Authorization header are NEVER logged.
 *   - The dispatcher's fail-closed rejection codes (`channel-not-public`,
 *     `gesture-required-origin-unsupported`, `origin-unsupported`) pass through
 *     as HTTP 403 with the exact LocalApiResult JSON.
 *
 * node:http only (packaging discipline — no new prod deps).
 *
 * SSE (`GET /v1/events`): after auth, the request is upgraded to a
 * `text/event-stream` and subscribed to the {@link StreamBroadcaster}. Each
 * `(channel, payload)` frame becomes one SSE message (`event: <channel>` +
 * `data: <JSON.stringify(payload)>`). A 15s heartbeat comment keeps proxies from
 * idling the socket; its timer is `unref()`-ed so it never holds the process
 * open. Every live stream is tracked so `close()` ends it AND runs its cleanup
 * (unsubscribe + clear heartbeat) — no dangling broadcaster subscriptions.
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { timingSafeEqual } from "node:crypto";
import type { AddressInfo } from "node:net";
import type { A2AHttpRouter } from "./a2a-router.js";
import type { LocalApi } from "./local-api.js";
import type { StreamBroadcaster } from "./stream-broadcaster.js";

/** Loopback bind host — the server MUST never default off-loopback. */
const DEFAULT_HOST = "127.0.0.1";
/** Ephemeral port — the OS assigns a free port; the actual value is read back. */
const DEFAULT_PORT = 0;
/** Request-body cap: 1 MiB. Over-cap bodies are rejected 413 + socket destroyed. */
const MAX_BODY_BYTES = 1024 * 1024;
/** JSON content type applied to every response. */
const JSON_CONTENT_TYPE = "application/json; charset=utf-8";
/** The origin tag attached to every dispatch from this transport. */
const HTTP_ORIGIN = "local-api" as const;
/** SSE content type applied to the /v1/events response. */
const SSE_CONTENT_TYPE = "text/event-stream; charset=utf-8";
/** SSE heartbeat interval: a `: ping` comment every 15s to defeat idle proxies. */
const SSE_HEARTBEAT_MS = 15_000;
/** SSE reconnection hint (ms) sent once on connect so clients back off sanely. */
const SSE_RETRY_MS = 3000;
/** Retry cap for OS-assigned ephemeral ports that Fetch clients cannot use. */
const EPHEMERAL_PORT_RETRY_LIMIT = 20;
/**
 * WHATWG Fetch blocks requests to these ports before a socket is opened. The
 * local API is consumed through `fetch`, so binding one of them makes the
 * discovery file advertise an unusable endpoint.
 */
const FETCH_FORBIDDEN_PORTS = new Set<number>([
  1, 7, 9, 11, 13, 15, 17, 19, 20, 21, 22, 23, 25, 37, 42, 43, 53, 69, 77, 79,
  87, 95, 101, 102, 103, 104, 109, 110, 111, 113, 115, 117, 119, 123, 135, 137,
  139, 143, 161, 179, 389, 427, 465, 512, 513, 514, 515, 526, 530, 531, 532,
  540, 548, 554, 556, 563, 587, 601, 636, 989, 990, 993, 995, 1719, 1720, 1723,
  2049, 3659, 4045, 4190, 5060, 5061, 6000, 6566, 6697, 10080,
]);

/** Configuration for {@link startLocalApiHttpServer}. */
export interface LocalApiHttpServerOptions {
  /** Injected external-surface dispatcher (the security seam). */
  api: LocalApi;
  /** Bearer secret required on every request (generated by lifecycle wiring). */
  secret: string;
  /** SSE fan-out source — wired now; consumed by a later commit's /v1/events. */
  broadcaster: StreamBroadcaster;
  /** Optional A2A v1 path multiplexer. Omitted unless its opt-in wire feature is enabled. */
  a2aRouter?: A2AHttpRouter;
  /** Bind host. Defaults to 127.0.0.1; MUST never default to 0.0.0.0. */
  host?: string;
  /** Bind port. Defaults to 0 (ephemeral); actual port read from address(). */
  port?: number;
  /** Optional dev log. NEVER receives the secret or the Authorization header. */
  log?: (message: string) => void;
}

/** A running loopback HTTP server for the local API. */
export interface LocalApiHttpServer {
  /** The actual bound port (resolved from address(), never the ephemeral 0). */
  port: number;
  /** Close the server and destroy idle keep-alive sockets so close never hangs. */
  close(): Promise<void>;
}

/** Write a JSON envelope with the fixed content type and an explicit status. */
function sendJson(res: ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body);
  res.writeHead(status, { "content-type": JSON_CONTENT_TYPE });
  res.end(payload);
}

/** Does WHATWG Fetch reject this HTTP port before trying the connection? */
function isFetchForbiddenPort(port: number): boolean {
  return FETCH_FORBIDDEN_PORTS.has(port) || (port >= 6665 && port <= 6669);
}

/**
 * Constant-time bearer check. A length mismatch short-circuits to `false`
 * (timingSafeEqual throws on unequal-length buffers; the length itself is not a
 * meaningful secret-leak vector here — the shape of `Bearer <secret>` is known).
 */
function isAuthorized(header: string | undefined, secret: string): boolean {
  if (typeof header !== "string") return false;
  const prefix = "Bearer ";
  if (!header.startsWith(prefix)) return false;
  const presented = Buffer.from(header.slice(prefix.length), "utf8");
  const expected = Buffer.from(secret, "utf8");
  if (presented.length !== expected.length) return false;
  return timingSafeEqual(presented, expected);
}

/** Read the request body with a hard 1 MiB cap; resolves null when over-cap. */
function readBody(req: IncomingMessage): Promise<string | null> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let total = 0;
    let overCap = false;
    req.on("data", (chunk: Buffer) => {
      if (overCap) return;
      total += chunk.length;
      if (total > MAX_BODY_BYTES) {
        overCap = true;
        resolve(null);
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (overCap) return;
      resolve(Buffer.concat(chunks).toString("utf8"));
    });
    req.on("error", reject);
  });
}

/**
 * Parse + validate a dispatch body. Returns the normalized request or null when
 * the body is malformed / not an object / missing a string `channel`.
 */
function parseDispatchBody(raw: string): { channel: string; args?: unknown } | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    return null;
  }
  const body = parsed as Record<string, unknown>;
  if (typeof body.channel !== "string") {
    return null;
  }
  return "args" in body ? { channel: body.channel, args: body.args } : { channel: body.channel };
}

/** Handle POST /v1/dispatch after auth has passed. */
async function handleDispatch(
  req: IncomingMessage,
  res: ServerResponse,
  api: LocalApi,
  log?: (message: string) => void,
): Promise<void> {
  const raw = await readBody(req);
  if (raw === null) {
    // Over-cap: respond then destroy the socket so a client streaming a huge
    // body cannot keep the connection alive.
    sendJson(res, 413, { ok: false, error: "payload-too-large" });
    req.socket.destroy();
    return;
  }
  const parsed = parseDispatchBody(raw);
  if (parsed === null) {
    sendJson(res, 400, { ok: false, error: "invalid-request" });
    return;
  }
  try {
    const result = await api.dispatch({
      channel: parsed.channel,
      ...("args" in parsed ? { args: parsed.args } : {}),
      origin: HTTP_ORIGIN,
    });
    // Success → 200; fail-closed rejection → 403; both carry the exact result.
    sendJson(res, result.ok ? 200 : 403, result);
  } catch (err) {
    // Never leak the thrown message to the client; log internally only.
    log?.(`dispatch handler threw: ${err instanceof Error ? err.message : String(err)}`);
    sendJson(res, 500, { ok: false, error: "internal-error" });
  }
}

/**
 * Handle GET /v1/events after auth has passed: upgrade to SSE and fan the
 * broadcaster's `(channel, payload)` frames out to this client. `liveStreams`
 * tracks a per-connection cleanup so `close()` can end every stream and run its
 * unsubscribe + heartbeat-clear (no dangling broadcaster subscriptions).
 */
function handleEvents(
  req: IncomingMessage,
  res: ServerResponse,
  broadcaster: StreamBroadcaster,
  liveStreams: Set<() => void>,
): void {
  res.writeHead(200, {
    "content-type": SSE_CONTENT_TYPE,
    "cache-control": "no-cache, no-transform",
    connection: "keep-alive",
  });
  // Disable Nagle so each frame flushes immediately (SSE is latency-sensitive).
  res.socket?.setNoDelay(true);
  // Preamble: reconnection hint + a comment so the client knows the stream lives.
  res.write(`retry: ${SSE_RETRY_MS}\n`);
  res.write(": connected\n\n");

  const subscription = broadcaster.subscribe((channel, payload) => {
    // `payload` may contain newlines only via JSON escaping, so one `data:` line
    // is sufficient and correct.
    res.write(`event: ${channel}\ndata: ${JSON.stringify(payload)}\n\n`);
  });

  const heartbeat = setInterval(() => {
    res.write(": ping\n\n");
  }, SSE_HEARTBEAT_MS);
  // Never let the heartbeat hold the process open.
  heartbeat.unref();

  let cleaned = false;
  // On server close(): end the response (which triggers the `close` events →
  // cleanup) and defensively run cleanup so the subscription is dropped even if
  // an ended socket does not re-emit `close`. Declared before `cleanup` so it can
  // be removed from `liveStreams` by the same reference that was added.
  const endStream = () => {
    res.end();
    cleanup();
  };
  const cleanup = () => {
    if (cleaned) return;
    cleaned = true;
    clearInterval(heartbeat);
    subscription();
    liveStreams.delete(endStream);
  };

  // Client disconnect (either half of the socket closing) → unsubscribe + clear.
  req.on("close", cleanup);
  res.on("close", cleanup);

  liveStreams.add(endStream);
}

/** Route a single authorized request. */
async function route(
  req: IncomingMessage,
  res: ServerResponse,
  api: LocalApi,
  broadcaster: StreamBroadcaster,
  liveStreams: Set<() => void>,
  a2aRouter: A2AHttpRouter | undefined,
  log?: (message: string) => void,
): Promise<void> {
  // Strip query/hash — routing is on the path only.
  const path = (req.url ?? "").split("?")[0].split("#")[0];
  const method = req.method ?? "GET";

  if (a2aRouter && (await a2aRouter.tryHandle(req, res, path, method))) {
    return;
  }

  if (path === "/v1/dispatch") {
    if (method !== "POST") {
      sendJson(res, 405, { ok: false, error: "method-not-allowed" });
      return;
    }
    await handleDispatch(req, res, api, log);
    return;
  }

  if (path === "/v1/events") {
    if (method !== "GET") {
      sendJson(res, 405, { ok: false, error: "method-not-allowed" });
      return;
    }
    handleEvents(req, res, broadcaster, liveStreams);
    return;
  }

  if (path === "/v1/health") {
    if (method !== "GET") {
      sendJson(res, 405, { ok: false, error: "method-not-allowed" });
      return;
    }
    sendJson(res, 200, { ok: true });
    return;
  }

  sendJson(res, 404, { ok: false, error: "not-found" });
}

/**
 * Start the loopback HTTP server. Resolves once listening, with the actual
 * bound port read from `server.address()`.
 */
export function startLocalApiHttpServer(
  opts: LocalApiHttpServerOptions,
): Promise<LocalApiHttpServer> {
  const { api, secret, broadcaster, a2aRouter, host = DEFAULT_HOST, port = DEFAULT_PORT, log } =
    opts;
  if (port !== DEFAULT_PORT && isFetchForbiddenPort(port)) {
    return Promise.reject(
      new Error(`local-api http server port ${port} is blocked by Fetch clients`),
    );
  }

  // Per-connection SSE stream enders — `close()` runs each to end the response
  // and unsubscribe from the broadcaster (no dangling subscriptions on shutdown).
  const liveStreams = new Set<() => void>();

  const server: Server = createServer((req, res) => {
    const path = (req.url ?? "").split("?")[0].split("#")[0];
    const method = req.method ?? "GET";
    // Agent Card discovery is the only public route. Every operation and every
    // pre-existing local API route still authenticates before processing.
    const isPublicAgentCard = a2aRouter?.isPublicAgentCardRequest(path, method) === true;
    if (!isPublicAgentCard && !isAuthorized(req.headers.authorization, secret)) {
      sendJson(res, 401, { ok: false, error: "unauthorized" });
      return;
    }
    void route(req, res, api, broadcaster, liveStreams, a2aRouter, log).catch((err) => {
      // Defensive: an unexpected error in the routing layer itself.
      log?.(`request routing error: ${err instanceof Error ? err.message : String(err)}`);
      if (!res.headersSent) {
        sendJson(res, 500, { ok: false, error: "internal-error" });
      } else {
        res.end();
      }
    });
  });

  return new Promise<LocalApiHttpServer>((resolve, reject) => {
    let attempts = 0;
    let settled = false;
    const rejectOnce = (err: Error) => {
      if (settled) return;
      settled = true;
      server.removeListener("error", onError);
      reject(err);
    };
    const onError = (err: Error) => {
      rejectOnce(err);
    };
    server.on("error", onError);
    const listen = () => {
      attempts += 1;
      server.listen(port, host, () => {
        const address = server.address() as AddressInfo | null;
        const boundPort = address?.port ?? 0;
        if (port === DEFAULT_PORT && isFetchForbiddenPort(boundPort)) {
          if (attempts >= EPHEMERAL_PORT_RETRY_LIMIT) {
            server.close(() => {
              rejectOnce(
                new Error(
                  `local-api http server received ${attempts} Fetch-blocked ephemeral ports`,
                ),
              );
            });
            return;
          }
          log?.(
            `local-api http server received Fetch-blocked ephemeral port ${boundPort}; retrying`,
          );
          server.close((closeErr) => {
            if (closeErr) {
              rejectOnce(closeErr);
              return;
            }
            listen();
          });
          return;
        }

        if (settled) return;
        settled = true;
        server.removeListener("error", onError);
        log?.(`local-api http server listening on ${host}:${boundPort}`);
        resolve({
          port: boundPort,
          close: () =>
            new Promise<void>((res, rej) => {
              // End every live SSE stream first: this unsubscribes from the
              // broadcaster (no dangling subscriptions) and lets server.close()
              // resolve instead of hanging on an open event-stream socket.
              for (const endStream of [...liveStreams]) {
                endStream();
              }
              // Destroy idle keep-alive sockets so close() never hangs.
              server.closeAllConnections();
              server.close((closeErr) => {
                if (!closeErr || (closeErr as { code?: string }).code === "ERR_SERVER_NOT_RUNNING") {
                  res();
                  return;
                }
                rej(closeErr);
              });
            }),
        });
      });
    };
    listen();
  });
}
