/**
 * http-server.ts — #1436 loopback HTTP transport for the local API (#1409
 * follow-up).
 *
 * Exposes the transport-agnostic {@link LocalApi} dispatcher over a
 * node:http server bound to loopback ONLY. This is the network edge for the
 * external surface: it never constructs services, it forwards validated
 * requests to the injected dispatcher, and it is fail-closed on every axis.
 *
 * SECURITY:
 *   - Bind host hard-defaults to 127.0.0.1 and MUST never default to 0.0.0.0 —
 *     the server is reachable only from the local machine.
 *   - EVERY route (health included) requires `Authorization: Bearer <secret>`
 *     with a constant-time compare. Missing/invalid → 401 before any other
 *     processing. The secret and the Authorization header are NEVER logged.
 *   - The dispatcher's fail-closed rejection codes (`channel-not-public`,
 *     `gesture-required-origin-unsupported`, `origin-unsupported`) pass through
 *     as HTTP 403 with the exact LocalApiResult JSON.
 *
 * node:http only (packaging discipline — no new prod deps). SSE (`/v1/events`)
 * is a later commit: the broadcaster option is accepted now so the signature is
 * final, but no event route is implemented here.
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { timingSafeEqual } from "node:crypto";
import type { AddressInfo } from "node:net";
import type { LocalApi } from "./local-api.js";
import type { StreamBroadcaster } from "./stream-broadcaster.js";

/** Loopback bind host — the server MUST never default off-loopback. */
const DEFAULT_HOST = "127.0.0.1";
/** Ephemeral port — the OS assigns a free port; the actual value is read back. */
const DEFAULT_PORT = 0;
/** Request-body cap: 1 MiB. Over-cap bodies are rejected 413 + socket destroyed. */
const MAX_BODY_BYTES = 1024 * 1024;
/** JSON content type applied to every response. */
const JSON_CONTENT_TYPE = "application/json; charset=utf-8";
/** The origin tag attached to every dispatch from this transport. */
const HTTP_ORIGIN = "local-api" as const;

/** Configuration for {@link startLocalApiHttpServer}. */
export interface LocalApiHttpServerOptions {
  /** Injected external-surface dispatcher (the security seam). */
  api: LocalApi;
  /** Bearer secret required on every request (generated by lifecycle wiring). */
  secret: string;
  /** SSE fan-out source — wired now; consumed by a later commit's /v1/events. */
  broadcaster: StreamBroadcaster;
  /** Bind host. Defaults to 127.0.0.1; MUST never default to 0.0.0.0. */
  host?: string;
  /** Bind port. Defaults to 0 (ephemeral); actual port read from address(). */
  port?: number;
  /** Optional dev log. NEVER receives the secret or the Authorization header. */
  log?: (message: string) => void;
}

/** A running loopback HTTP server for the local API. */
export interface LocalApiHttpServer {
  /** The actual bound port (resolved from address(), never the ephemeral 0). */
  port: number;
  /** Close the server and destroy idle keep-alive sockets so close never hangs. */
  close(): Promise<void>;
}

/** Write a JSON envelope with the fixed content type and an explicit status. */
function sendJson(res: ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body);
  res.writeHead(status, { "content-type": JSON_CONTENT_TYPE });
  res.end(payload);
}

/**
 * Constant-time bearer check. A length mismatch short-circuits to `false`
 * (timingSafeEqual throws on unequal-length buffers; the length itself is not a
 * meaningful secret-leak vector here — the shape of `Bearer <secret>` is known).
 */
function isAuthorized(header: string | undefined, secret: string): boolean {
  if (typeof header !== "string") return false;
  const prefix = "Bearer ";
  if (!header.startsWith(prefix)) return false;
  const presented = Buffer.from(header.slice(prefix.length), "utf8");
  const expected = Buffer.from(secret, "utf8");
  if (presented.length !== expected.length) return false;
  return timingSafeEqual(presented, expected);
}

/** Read the request body with a hard 1 MiB cap; resolves null when over-cap. */
function readBody(req: IncomingMessage): Promise<string | null> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let total = 0;
    let overCap = false;
    req.on("data", (chunk: Buffer) => {
      if (overCap) return;
      total += chunk.length;
      if (total > MAX_BODY_BYTES) {
        overCap = true;
        resolve(null);
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (overCap) return;
      resolve(Buffer.concat(chunks).toString("utf8"));
    });
    req.on("error", reject);
  });
}

/**
 * Parse + validate a dispatch body. Returns the normalized request or null when
 * the body is malformed / not an object / missing a string `channel`.
 */
function parseDispatchBody(raw: string): { channel: string; args?: unknown } | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    return null;
  }
  const body = parsed as Record<string, unknown>;
  if (typeof body.channel !== "string") {
    return null;
  }
  return "args" in body ? { channel: body.channel, args: body.args } : { channel: body.channel };
}

/** Handle POST /v1/dispatch after auth has passed. */
async function handleDispatch(
  req: IncomingMessage,
  res: ServerResponse,
  api: LocalApi,
  log?: (message: string) => void,
): Promise<void> {
  const raw = await readBody(req);
  if (raw === null) {
    // Over-cap: respond then destroy the socket so a client streaming a huge
    // body cannot keep the connection alive.
    sendJson(res, 413, { ok: false, error: "payload-too-large" });
    req.socket.destroy();
    return;
  }
  const parsed = parseDispatchBody(raw);
  if (parsed === null) {
    sendJson(res, 400, { ok: false, error: "invalid-request" });
    return;
  }
  try {
    const result = await api.dispatch({
      channel: parsed.channel,
      ...("args" in parsed ? { args: parsed.args } : {}),
      origin: HTTP_ORIGIN,
    });
    // Success → 200; fail-closed rejection → 403; both carry the exact result.
    sendJson(res, result.ok ? 200 : 403, result);
  } catch (err) {
    // Never leak the thrown message to the client; log internally only.
    log?.(`dispatch handler threw: ${err instanceof Error ? err.message : String(err)}`);
    sendJson(res, 500, { ok: false, error: "internal-error" });
  }
}

/** Route a single authorized request. */
async function route(
  req: IncomingMessage,
  res: ServerResponse,
  api: LocalApi,
  log?: (message: string) => void,
): Promise<void> {
  // Strip query/hash — routing is on the path only.
  const path = (req.url ?? "").split("?")[0].split("#")[0];
  const method = req.method ?? "GET";

  if (path === "/v1/dispatch") {
    if (method !== "POST") {
      sendJson(res, 405, { ok: false, error: "method-not-allowed" });
      return;
    }
    await handleDispatch(req, res, api, log);
    return;
  }

  if (path === "/v1/health") {
    if (method !== "GET") {
      sendJson(res, 405, { ok: false, error: "method-not-allowed" });
      return;
    }
    sendJson(res, 200, { ok: true });
    return;
  }

  sendJson(res, 404, { ok: false, error: "not-found" });
}

/**
 * Start the loopback HTTP server. Resolves once listening, with the actual
 * bound port read from `server.address()`.
 */
export function startLocalApiHttpServer(
  opts: LocalApiHttpServerOptions,
): Promise<LocalApiHttpServer> {
  const { api, secret, host = DEFAULT_HOST, port = DEFAULT_PORT, log } = opts;

  const server: Server = createServer((req, res) => {
    // Auth on EVERY route before any other processing. Never log the secret or
    // the Authorization header.
    if (!isAuthorized(req.headers.authorization, secret)) {
      sendJson(res, 401, { ok: false, error: "unauthorized" });
      return;
    }
    void route(req, res, api, log).catch((err) => {
      // Defensive: an unexpected error in the routing layer itself.
      log?.(`request routing error: ${err instanceof Error ? err.message : String(err)}`);
      if (!res.headersSent) {
        sendJson(res, 500, { ok: false, error: "internal-error" });
      } else {
        res.end();
      }
    });
  });

  return new Promise<LocalApiHttpServer>((resolve, reject) => {
    const onError = (err: Error) => {
      server.removeListener("error", onError);
      reject(err);
    };
    server.on("error", onError);
    server.listen(port, host, () => {
      server.removeListener("error", onError);
      const address = server.address() as AddressInfo | null;
      const boundPort = address?.port ?? 0;
      log?.(`local-api http server listening on ${host}:${boundPort}`);
      resolve({
        port: boundPort,
        close: () =>
          new Promise<void>((res, rej) => {
            // Destroy idle keep-alive sockets so close() never hangs.
            server.closeAllConnections();
            server.close((closeErr) => (closeErr ? rej(closeErr) : res()));
          }),
      });
    });
  });
}
