/**
 * agent-action-requester.test.ts
 *
 * Covers:
 *   (a) decision.choice round-trips correctly from gate to caller
 *   (b) nonce/HMAC are generated by the gate, NOT by the caller
 *   (c) error path: gate timeout returns deny-once (no throw)
 *   (d) hostApi.agentApproval.respond round-trips through gate.resolve
 *
 * Note: a `list()` namespace was intentionally removed — see plugins/types.ts.
 * Tests only cover the respond round-trip path that is actually wired.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { requestAgentApproval, ApprovalIssuerRegistry } from "../agent-action-requester.js";
import type { ApprovalGate } from "../approval-gate.js";
import type { ApprovalDecision } from "../approval-gate.js";

// ─── Mock ApprovalGate ────────────────────────────────

function makeMockGate(resolveWith: ApprovalDecision) {
  return {
    requestAndWait: vi.fn(async () => resolveWith),
  } as unknown as ApprovalGate;
}

const BASE_INPUT = {
  toolName: "agent_hub_decide_approval_with_host",
  args: { approvalId: 42, choice: "allow-once" },
  reason: "승인 요청: 결재 ID 42",
  source: "plugin" as const,
  sourcePluginId: "agent-hub",
  scope: "agent_external_api_call",
};

// ─── Tests ────────────────────────────────────────────

describe("requestAgentApproval", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("(a) returns the choice from the gate decision", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "allow-once",
      nonce: "aabbcc",
      hmac: "deadbeef",
    });

    const choice = await requestAgentApproval(gate, BASE_INPUT);
    expect(choice).toBe("allow-once");
  });

  it("(a) round-trips deny-once choice correctly", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "deny-once",
      nonce: "aabbcc",
      hmac: "deadbeef",
    });

    const choice = await requestAgentApproval(gate, BASE_INPUT);
    expect(choice).toBe("deny-once");
  });

  it("(a) round-trips allow-always choice correctly", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "allow-always",
      nonce: "aabbcc",
      hmac: "deadbeef",
    });

    const choice = await requestAgentApproval(gate, BASE_INPUT);
    expect(choice).toBe("allow-always");
  });

  it("(b) nonce/HMAC are NOT supplied by the caller — only gate fields reach requestAndWait", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "allow-once",
      nonce: "gate-nonce",
      hmac: "gate-hmac",
    });

    await requestAgentApproval(gate, BASE_INPUT);

    const [calledReq] = (gate.requestAndWait as ReturnType<typeof vi.fn>).mock.calls[0] as [
      Parameters<ApprovalGate["requestAndWait"]>[0],
    ];

    // The request passed to the gate must NOT include nonce or hmac — those
    // are minted internally by ApprovalGate (§D2 confused-deputy defense).
    expect(calledReq).not.toHaveProperty("nonce");
    expect(calledReq).not.toHaveProperty("hmac");

    // Must include the core fields the gate needs.
    expect(calledReq.category).toBe("tool");
    expect(calledReq.toolName).toBe(BASE_INPUT.toolName);
    expect(calledReq.args).toEqual(BASE_INPUT.args);
    expect(calledReq.reason).toBe(BASE_INPUT.reason);
    expect(calledReq.source).toBe("plugin");
    expect(typeof calledReq.id).toBe("string");
    expect(typeof calledReq.createdAt).toBe("number");
  });

  it("(b) each call generates a unique request ID", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "allow-once",
      nonce: "n",
      hmac: "h",
    });

    await requestAgentApproval(gate, BASE_INPUT);
    await requestAgentApproval(gate, BASE_INPUT);

    const calls = (gate.requestAndWait as ReturnType<typeof vi.fn>).mock.calls as [
      Parameters<ApprovalGate["requestAndWait"]>[0],
    ][];
    const id1 = calls[0][0].id;
    const id2 = calls[1][0].id;
    expect(id1).not.toBe(id2);
  });

  it("(c) gate timeout (deny-once) is returned without throwing", async () => {
    // Gate returns deny-once on timeout — must not throw
    const gate = makeMockGate({
      requestId: "timeout-id",
      choice: "deny-once",
    });

    const choice = await requestAgentApproval(gate, BASE_INPUT);
    expect(choice).toBe("deny-once");
  });

  it("(c) gate rejection propagates as thrown error", async () => {
    const gate = {
      requestAndWait: vi.fn(async () => {
        throw new Error("gate internal error");
      }),
    } as unknown as ApprovalGate;

    await expect(requestAgentApproval(gate, BASE_INPUT)).rejects.toThrow(
      "gate internal error",
    );
  });
});

// ─── (d) hostApi.agentApproval.respond round-trips through gate.resolve ──────
//
// This tests the main-process respond path used by the plugin's
// decide-approval-with-host handler (Lane 5 corrected architecture).
// We simulate how initPluginRuntime wires agentApproval.respond() to
// approvalGate.resolve().

describe("hostApi.agentApproval.respond — gate.resolve round-trip", () => {
  it("(d) respond(id, choice, nonce, hmac) calls gate.resolve with matching decision", () => {
    // Minimal mock of ApprovalGate.resolve() — synchronous per the real API.
    const mockResolve = vi.fn();
    const gate = { resolve: mockResolve } as unknown as ApprovalGate;

    // Simulate the wiring inside initPluginRuntime's createHostApi factory:
    const agentApproval = {
      respond: async (
        requestId: string,
        choice: ApprovalDecision["choice"],
        nonce?: string,
        hmac?: string,
      ): Promise<void> => {
        gate.resolve(requestId, { requestId, choice, nonce, hmac });
      },
    };

    const requestId = "req-42";
    const choice = "allow-once" as const;
    const nonce = "aabbcc";
    const hmac = "deadbeef";

    void agentApproval.respond(requestId, choice, nonce, hmac);

    expect(mockResolve).toHaveBeenCalledOnce();
    expect(mockResolve).toHaveBeenCalledWith(requestId, {
      requestId,
      choice,
      nonce,
      hmac,
    });
  });

  it("(d) respond without nonce/hmac still calls gate.resolve (no §D2 crash)", () => {
    const mockResolve = vi.fn();
    const gate = { resolve: mockResolve } as unknown as ApprovalGate;

    const agentApproval = {
      respond: async (
        requestId: string,
        choice: ApprovalDecision["choice"],
        nonce?: string,
        hmac?: string,
      ): Promise<void> => {
        gate.resolve(requestId, { requestId, choice, nonce, hmac });
      },
    };

    void agentApproval.respond("req-99", "deny-once");

    expect(mockResolve).toHaveBeenCalledWith("req-99", {
      requestId: "req-99",
      choice: "deny-once",
      nonce: undefined,
      hmac: undefined,
    });
  });
});

// ─── Group A — ApprovalIssuerRegistry.purgeStalerThan ────────────────────────

describe("ApprovalIssuerRegistry.purgeStalerThan", () => {
  it("purges entries older than maxAgeMs", () => {
    const r = new ApprovalIssuerRegistry();
    const old = "req-old";
    r.record(old, "plugin-a", "agent_file_share");
    // simulate clock advance
    vi.useFakeTimers();
    vi.setSystemTime(Date.now() + 60_000);
    const fresh = "req-fresh";
    r.record(fresh, "plugin-a", "agent_file_share");
    const purged = r.purgeStalerThan(30_000);
    expect(purged).toBe(1); // old purged
    expect(r.peek(fresh)).toBeDefined();
    expect(r.peek(old)).toBeUndefined();
    vi.useRealTimers();
  });

  it("returns 0 when nothing is older than maxAgeMs", () => {
    const r = new ApprovalIssuerRegistry();
    r.record("a", "p", "s");
    expect(r.purgeStalerThan(60_000)).toBe(0);
  });

  it("boundary: entry exactly at cutoff is preserved (uses < not <=)", () => {
    const r = new ApprovalIssuerRegistry();
    vi.useFakeTimers();
    const t0 = Date.now();
    vi.setSystemTime(t0);
    r.record("a", "p", "s");
    vi.setSystemTime(t0 + 30_000);
    expect(r.purgeStalerThan(30_000)).toBe(0); // recordedAt(t0) < cutoff(t0)? false → preserved
    vi.useRealTimers();
  });
});

// ─── Group B — requestAgentApproval try-finally entry cleanup ────────────────

describe("requestAgentApproval try-finally cleanup", () => {
  it("deletes registry entry when gate.requestAndWait throws", async () => {
    const r = new ApprovalIssuerRegistry();
    const gate = {
      requestAndWait: vi.fn(async () => {
        throw new Error("gate failure");
      }),
    };
    await expect(
      requestAgentApproval(
        gate as unknown as ApprovalGate,
        { requestId: "req-x", toolName: "t", args: {}, reason: "r", source: "plugin", sourcePluginId: "plugin-a", scope: "agent_file_share" },
        r,
      ),
    ).rejects.toThrow("gate failure");
    expect(r.peek("req-x")).toBeUndefined(); // cleaned up via finally
  });

  it("does NOT delete entry on success (registry consumed by respond path)", async () => {
    const r = new ApprovalIssuerRegistry();
    const gate = {
      requestAndWait: vi.fn(async () => ({
        requestId: "req-y",
        choice: "allow-once" as const,
        nonce: "n",
        hmac: "h",
      })),
    };
    const choice = await requestAgentApproval(
      gate as unknown as ApprovalGate,
      { toolName: "t", args: {}, reason: "r", source: "plugin", sourcePluginId: "plugin-a", scope: "agent_file_share" },
      r,
    );
    expect(choice).toBe("allow-once");
    // The requestId is generated internally — check registry has exactly 1 entry
    expect(r.size).toBe(1); // settled=true, finally skips delete
  });
});
