/**
 * agent-action-requester.test.ts
 *
 * Covers:
 *   (a) decision.choice round-trips correctly from gate to caller
 *   (b) nonce/HMAC are generated by the gate, NOT by the caller
 *   (c) error path: gate timeout returns deny-once (no throw)
 *   (d) hostApi.agentApproval.respond round-trips through gate.resolve
 *   (e) purgeStalerThan: age-based eviction — old entries purged, new entries survive
 *
 * Note: a `list()` namespace was intentionally removed — see plugins/types.ts.
 * Tests only cover the respond round-trip path that is actually wired.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { requestAgentApproval, ApprovalIssuerRegistry } from "../agent-action-requester.js";
import type { ApprovalGate } from "../approval-gate.js";
import type { ApprovalDecision } from "../approval-gate.js";

// ─── Mock ApprovalGate ────────────────────────────────

function makeMockGate(resolveWith: ApprovalDecision) {
  return {
    requestAndWait: vi.fn(async () => resolveWith),
  } as unknown as ApprovalGate;
}

const BASE_INPUT = {
  toolName: "agent_hub_decide_approval_with_host",
  args: { approvalId: 42, choice: "allow-once" },
  reason: "승인 요청: 결재 ID 42",
  source: "plugin" as const,
  sourcePluginId: "agent-hub",
  scope: "agent_external_api_call",
};

// ─── Tests ────────────────────────────────────────────

describe("requestAgentApproval", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("(a) returns the choice from the gate decision", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "allow-once",
      nonce: "aabbcc",
      hmac: "deadbeef",
    });

    const choice = await requestAgentApproval(gate, BASE_INPUT, new ApprovalIssuerRegistry());
    expect(choice).toBe("allow-once");
  });

  it("(a) round-trips deny-once choice correctly", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "deny-once",
      nonce: "aabbcc",
      hmac: "deadbeef",
    });

    const choice = await requestAgentApproval(gate, BASE_INPUT, new ApprovalIssuerRegistry());
    expect(choice).toBe("deny-once");
  });

  it("(a) round-trips allow-always choice correctly", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "allow-always",
      nonce: "aabbcc",
      hmac: "deadbeef",
    });

    const choice = await requestAgentApproval(gate, BASE_INPUT, new ApprovalIssuerRegistry());
    expect(choice).toBe("allow-always");
  });

  it("(b) nonce/HMAC are NOT supplied by the caller — only gate fields reach requestAndWait", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "allow-once",
      nonce: "gate-nonce",
      hmac: "gate-hmac",
    });

    await requestAgentApproval(gate, BASE_INPUT, new ApprovalIssuerRegistry());

    const [calledReq] = (gate.requestAndWait as ReturnType<typeof vi.fn>).mock.calls[0] as [
      Parameters<ApprovalGate["requestAndWait"]>[0],
    ];

    // The request passed to the gate must NOT include nonce or hmac — those
    // are minted internally by ApprovalGate (§D2 confused-deputy defense).
    expect(calledReq).not.toHaveProperty("nonce");
    expect(calledReq).not.toHaveProperty("hmac");

    // Must include the core fields the gate needs.
    expect(calledReq.category).toBe("tool");
    expect(calledReq.toolName).toBe(BASE_INPUT.toolName);
    expect(calledReq.args).toEqual(BASE_INPUT.args);
    expect(calledReq.reason).toBe(BASE_INPUT.reason);
    expect(calledReq.source).toBe("plugin");
    expect(typeof calledReq.id).toBe("string");
    expect(typeof calledReq.createdAt).toBe("number");
  });

  it("(b) each call generates a unique request ID", async () => {
    const gate = makeMockGate({
      requestId: "test-id",
      choice: "allow-once",
      nonce: "n",
      hmac: "h",
    });

    const registry = new ApprovalIssuerRegistry();
    await requestAgentApproval(gate, BASE_INPUT, registry);
    await requestAgentApproval(gate, BASE_INPUT, registry);

    const calls = (gate.requestAndWait as ReturnType<typeof vi.fn>).mock.calls as [
      Parameters<ApprovalGate["requestAndWait"]>[0],
    ][];
    const id1 = calls[0][0].id;
    const id2 = calls[1][0].id;
    expect(id1).not.toBe(id2);
  });

  it("(c) gate timeout (deny-once) is returned without throwing", async () => {
    // Gate returns deny-once on timeout — must not throw
    const gate = makeMockGate({
      requestId: "timeout-id",
      choice: "deny-once",
    });

    const choice = await requestAgentApproval(gate, BASE_INPUT, new ApprovalIssuerRegistry());
    expect(choice).toBe("deny-once");
  });

  it("(c) gate rejection propagates as thrown error", async () => {
    const gate = {
      requestAndWait: vi.fn(async () => {
        throw new Error("gate internal error");
      }),
    } as unknown as ApprovalGate;

    await expect(
      requestAgentApproval(gate, BASE_INPUT, new ApprovalIssuerRegistry()),
    ).rejects.toThrow("gate internal error");
  });
});

// ─── (d) hostApi.agentApproval.respond round-trips through gate.resolve ──────
//
// This tests the main-process respond path used by the plugin's
// decide-approval-with-host handler (Lane 5 corrected architecture).
// We simulate how initPluginRuntime wires agentApproval.respond() to
// approvalGate.resolve().

describe("hostApi.agentApproval.respond — gate.resolve round-trip", () => {
  it("(d) respond(id, choice, nonce, hmac) calls gate.resolve with matching decision", () => {
    // Minimal mock of ApprovalGate.resolve() — synchronous per the real API.
    const mockResolve = vi.fn();
    const gate = { resolve: mockResolve } as unknown as ApprovalGate;

    // Simulate the wiring inside initPluginRuntime's createHostApi factory:
    const agentApproval = {
      respond: async (
        requestId: string,
        choice: ApprovalDecision["choice"],
        nonce?: string,
        hmac?: string,
      ): Promise<void> => {
        gate.resolve(requestId, { requestId, choice, nonce, hmac });
      },
    };

    const requestId = "req-42";
    const choice = "allow-once" as const;
    const nonce = "aabbcc";
    const hmac = "deadbeef";

    void agentApproval.respond(requestId, choice, nonce, hmac);

    expect(mockResolve).toHaveBeenCalledOnce();
    expect(mockResolve).toHaveBeenCalledWith(requestId, {
      requestId,
      choice,
      nonce,
      hmac,
    });
  });

  it("(d) respond without nonce/hmac still calls gate.resolve (no §D2 crash)", () => {
    const mockResolve = vi.fn();
    const gate = { resolve: mockResolve } as unknown as ApprovalGate;

    const agentApproval = {
      respond: async (
        requestId: string,
        choice: ApprovalDecision["choice"],
        nonce?: string,
        hmac?: string,
      ): Promise<void> => {
        gate.resolve(requestId, { requestId, choice, nonce, hmac });
      },
    };

    void agentApproval.respond("req-99", "deny-once");

    expect(mockResolve).toHaveBeenCalledWith("req-99", {
      requestId: "req-99",
      choice: "deny-once",
      nonce: undefined,
      hmac: undefined,
    });
  });
});

// ─── (e) ApprovalIssuerRegistry.purgeStalerThan — timestamp-based eviction ───
//
// Verifies that purgeStalerThan() evicts only entries older than maxAgeMs
// and returns the correct purge count. Newer entries must survive.

describe("ApprovalIssuerRegistry.purgeStalerThan", () => {
  beforeEach(() => { vi.useFakeTimers(); });
  afterEach(() => { vi.useRealTimers(); });

  it("(e) purges entries older than maxAgeMs and returns purge count", () => {
    const registry = new ApprovalIssuerRegistry();

    // Record two entries at t=0
    vi.setSystemTime(0);
    registry.record("req-old-1", "plugin-a", "scope-x");
    registry.record("req-old-2", "plugin-b", "scope-y");

    // Advance time by 6 minutes — entries are now 6 min old
    vi.setSystemTime(6 * 60 * 1000);

    // Record a fresh entry at t=6min
    registry.record("req-new", "plugin-c", "scope-z");

    // Purge entries older than 5 minutes
    const purged = registry.purgeStalerThan(5 * 60 * 1000);

    expect(purged).toBe(2);
    expect(registry.size).toBe(1);
    // New entry survives
    expect(registry.peek("req-new")).toBeDefined();
    // Old entries are gone
    expect(registry.peek("req-old-1")).toBeUndefined();
    expect(registry.peek("req-old-2")).toBeUndefined();
  });

  it("(e) returns 0 and leaves registry intact when no entries are stale", () => {
    const registry = new ApprovalIssuerRegistry();

    vi.setSystemTime(0);
    registry.record("req-fresh-1", "plugin-a", "scope-x");
    registry.record("req-fresh-2", "plugin-b", "scope-y");

    // Only 1 minute has passed — well within 5-minute window
    vi.setSystemTime(60 * 1000);

    const purged = registry.purgeStalerThan(5 * 60 * 1000);

    expect(purged).toBe(0);
    expect(registry.size).toBe(2);
  });

  it("(e) purges all entries when all are older than maxAgeMs", () => {
    const registry = new ApprovalIssuerRegistry();

    vi.setSystemTime(0);
    registry.record("req-a", "plugin-a", "scope-a");
    registry.record("req-b", "plugin-b", "scope-b");
    registry.record("req-c", "plugin-c", "scope-c");

    vi.setSystemTime(10 * 60 * 1000); // 10 minutes later

    const purged = registry.purgeStalerThan(5 * 60 * 1000);

    expect(purged).toBe(3);
    expect(registry.size).toBe(0);
  });

  it("(e) purges only stale entries when registry has mixed ages", () => {
    const registry = new ApprovalIssuerRegistry();

    // Stale at t=0
    vi.setSystemTime(0);
    registry.record("req-stale", "plugin-a", "scope-a");

    // Fresh at t=4min (within 5-min window)
    vi.setSystemTime(4 * 60 * 1000);
    registry.record("req-fresh", "plugin-b", "scope-b");

    // Now at t=5min30s — stale entry is 5m30s old, fresh is 1m30s old
    vi.setSystemTime(5 * 60 * 1000 + 30 * 1000);

    const purged = registry.purgeStalerThan(5 * 60 * 1000);

    expect(purged).toBe(1);
    expect(registry.size).toBe(1);
    expect(registry.peek("req-stale")).toBeUndefined();
    expect(registry.peek("req-fresh")).toBeDefined();
  });
});
