import assert from "node:assert/strict";
import test from "node:test";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { deflateSync } from "node:zlib";
import { readBuildSourceIdentity } from "../../scripts/lib/build-source-identity.mjs";

function png(level, fill = 0x40) {
  const chunk = (name, body) => {
    const size = Buffer.alloc(4);
    size.writeUInt32BE(body.length);
    // The comparison reads chunk bodies; CRC bytes are not image pixels.
    return Buffer.concat([size, Buffer.from(name), body, Buffer.alloc(4)]);
  };
  const header = Buffer.alloc(13);
  header.writeUInt32BE(4, 0);
  header.writeUInt32BE(4, 4);
  header[8] = 8;
  header[9] = 6;
  const pixels = Buffer.concat(Array.from({ length: 4 }, () => Buffer.concat([Buffer.from([0]), Buffer.alloc(16, fill)])));
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", header), chunk("IDAT", deflateSync(pixels, { level })), chunk("IEND", Buffer.alloc(0)),
  ]);
}

function fixture(t) {
  const root = mkdtempSync(join(tmpdir(), "lvis-build-identity-"));
  t.after(() => rmSync(root, { recursive: true, force: true, maxRetries: 3 }));
  const env = { ...process.env };
  for (const name of Object.keys(env)) if (name.startsWith("GIT_")) delete env[name];
  const git = (...args) => execFileSync("git", ["-C", root, "-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "-c", "commit.gpgsign=false", ...args], { env, encoding: "utf8" });
  git("init", "--quiet");
  mkdirSync(join(root, "build"));
  writeFileSync(join(root, ".gitignore"), "build/generated-assets.json\n");
  writeFileSync(join(root, "main.ts"), "export const value = 1;\n");
  writeFileSync(join(root, "build/icon.png"), png(0));
  writeFileSync(join(root, "build/generated-assets.json"), JSON.stringify(["build/icon.png"]));
  git("add", ".");
  git("commit", "--quiet", "-m", "fixture source");
  return { root, git };
}

test("records clean commit identity and scrubs an ambient Git repository override", (t) => {
  const { root, git } = fixture(t);
  const previous = process.env.GIT_DIR;
  process.env.GIT_DIR = "/nonexistent/ambient-repository";
  try {
    assert.deepEqual(readBuildSourceIdentity(root), {
      commit: git("rev-parse", "HEAD").trim(), tree: git("rev-parse", "HEAD^{tree}").trim(),
      dirty: false, generatedOutputs: {},
    });
  } finally {
    if (previous === undefined) delete process.env.GIT_DIR;
    else process.env.GIT_DIR = previous;
  }
});

test("records exact generated bytes only after the existing decoded-image guard accepts them", (t) => {
  const { root } = fixture(t);
  const encoded = png(9);
  writeFileSync(join(root, "build/icon.png"), encoded);
  assert.deepEqual(readBuildSourceIdentity(root).generatedOutputs, {
    "build/icon.png": { bytes: encoded.length, sha256: createHash("sha256").update(encoded).digest("hex") },
  });
  assert.equal(readBuildSourceIdentity(root).dirty, false);
  writeFileSync(join(root, "build/icon.png"), png(9, 0x7f));
  assert.equal(readBuildSourceIdentity(root).dirty, true);
  assert.deepEqual(readBuildSourceIdentity(root).generatedOutputs, {});
});

test("never exempts source edits, staged edits, or untracked files", (t) => {
  const { root, git } = fixture(t);
  writeFileSync(join(root, "build/icon.png"), png(9));
  writeFileSync(join(root, "main.ts"), "export const value = 2;\n");
  git("add", "main.ts");
  assert.equal(readBuildSourceIdentity(root).dirty, true);
  git("restore", "--staged", "--worktree", "main.ts");
  writeFileSync(join(root, "untracked.ts"), "export {};\n");
  assert.equal(readBuildSourceIdentity(root).dirty, true);
});

test("listing a handwritten file in the generator manifest cannot exempt its edits", (t) => {
  const { root } = fixture(t);
  writeFileSync(join(root, "build/generated-assets.json"), JSON.stringify(["main.ts"]));
  writeFileSync(join(root, "main.ts"), "export const value = 2;\n");
  const identity = readBuildSourceIdentity(root);
  assert.equal(identity.dirty, true);
  assert.deepEqual(identity.generatedOutputs, {});
});
