import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { deflateSync } from "node:zlib";
import { afterEach, describe, expect, it } from "vitest";

const REPO_ROOT = process.cwd();
const SCRIPT = resolve(REPO_ROOT, "scripts/check-generated-assets.mjs");
const MANIFEST = "build/generated-assets.json";
const nodeCommand = process.env.LVIS_TEST_NODE_EXEC_PATH ?? process.execPath;
const roots: string[] = [];

// Git exports these to hooks, and they outrank `-C`. The suite itself runs
// from the pre-push hook, so inheriting them would point both the fixtures and
// the guard at this repository instead of the temporary one.
const AMBIENT_GIT_VARS = [
  "GIT_DIR",
  "GIT_WORK_TREE",
  "GIT_COMMON_DIR",
  "GIT_INDEX_FILE",
  "GIT_OBJECT_DIRECTORY",
  "GIT_PREFIX",
] as const;

function envWithout(names: readonly string[]): NodeJS.ProcessEnv {
  const env = { ...process.env };
  for (const name of names) delete env[name];
  return env;
}

/**
 * Env for the cases that build throwaway repositories whose bytes they control.
 * The platform-specific encoder difference the guard skips for does not apply
 * to them, so the skip is forced off; without it they would pass by skipping on
 * every platform but Windows, testing nothing.
 *
 * NOT for the real-checkout case below. That one inspects committed blobs the
 * test did not author — win32-generated bytes that a darwin or linux encoder
 * reproduces differently — which is precisely the situation the platform skip
 * exists for. Forcing there turned a documented encoder difference into a
 * failure and blocked every push from a non-Windows machine.
 */
function forcedEnv(names: readonly string[]): NodeJS.ProcessEnv {
  const env = envWithout(names);
  env.LVIS_GENERATED_ASSETS_FORCE = "1";
  return env;
}

function run(root: string, env: NodeJS.ProcessEnv = forcedEnv(AMBIENT_GIT_VARS)) {
  return spawnSync(nodeCommand, [SCRIPT, "--root", root], {
    cwd: REPO_ROOT,
    encoding: "utf-8",
    env,
  });
}

function git(root: string, args: string[]) {
  const result = spawnSync(
    "git",
    [
      "-C",
      root,
      "-c",
      "user.email=guard@test.invalid",
      "-c",
      "user.name=guard",
      "-c",
      "commit.gpgsign=false",
      ...args,
    ],
    { encoding: "utf-8", env: forcedEnv(AMBIENT_GIT_VARS) },
  );
  if (result.status !== 0) {
    throw new Error(`git ${args.join(" ")} failed: ${result.stderr}`);
  }
  return result;
}

function write(root: string, rel: string, contents: string): void {
  const path = join(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, "utf-8");
}

function writeBytes(root: string, rel: string, contents: Buffer): void {
  const path = join(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
}

/** Replace a tracked asset's committed bytes, so HEAD holds `contents`. */
function commitIco(root: string, rel: string, contents: Buffer): void {
  writeBytes(root, rel, contents);
  git(root, ["add", rel]);
  git(root, ["commit", "--quiet", "-m", "seed image"]);
}

const CRC_TABLE = Array.from({ length: 256 }, (_unused, index) => {
  let value = index;
  for (let bit = 0; bit < 8; bit += 1) {
    value = value & 1 ? 0xed_b8_83_20 ^ (value >>> 1) : value >>> 1;
  }
  return value >>> 0;
});

function crc32(bytes: Buffer): number {
  let value = 0xff_ff_ff_ff;
  for (const byte of bytes) value = CRC_TABLE[(value ^ byte) & 0xff]! ^ (value >>> 8);
  return (value ^ 0xff_ff_ff_ff) >>> 0;
}

function pngChunk(type: string, body: Buffer): Buffer {
  const header = Buffer.alloc(4);
  header.writeUInt32BE(body.length);
  const typed = Buffer.concat([Buffer.from(type, "ascii"), body]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(typed));
  return Buffer.concat([header, typed, crc]);
}

/** One 4x4 RGBA scanline block: every row is filter byte 0 then `fill`. */
const PIXELS = Buffer.concat(
  Array.from({ length: 4 }, () => Buffer.concat([Buffer.from([0]), Buffer.alloc(16, 0x40)])),
);
const OTHER_PIXELS = Buffer.concat(
  Array.from({ length: 4 }, () => Buffer.concat([Buffer.from([0]), Buffer.alloc(16, 0x7f)])),
);

/** A single-image ICO whose PNG payload is deflated at `level`. */
function icoWith(pixels: Buffer, level: number): Buffer {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(4, 0);
  ihdr.writeUInt32BE(4, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // RGBA
  const png = Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", deflateSync(pixels, { level })),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
  const header = Buffer.alloc(6);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(1, 4);
  const entry = Buffer.alloc(16);
  entry[0] = 4;
  entry[1] = 4;
  entry.writeUInt16LE(1, 4); // planes
  entry.writeUInt16LE(32, 6); // bits per pixel
  entry.writeUInt32LE(png.length, 8);
  entry.writeUInt32LE(header.length + entry.length, 12);
  return Buffer.concat([header, entry, png]);
}

function writeManifest(root: string, paths: string[]): void {
  write(root, MANIFEST, `${JSON.stringify(paths, null, 2)}\n`);
}

/**
 * A throwaway repository holding one tracked generated asset committed with
 * the bytes the generator is pretending to have produced, so a later rewrite
 * of that file is exactly the divergence the guard exists to catch.
 */
function createRepo(): string {
  const root = mkdtempSync(join(tmpdir(), "lvis-generated-assets-"));
  roots.push(root);
  git(root, ["init", "--quiet"]);
  write(root, ".gitignore", "build/generated-assets.json\nbuild/icon.png\n");
  write(root, "build/installerIcon.ico", "committed-bytes");
  git(root, ["add", ".gitignore", "build/installerIcon.ico"]);
  git(root, ["commit", "--quiet", "-m", "seed"]);
  writeManifest(root, ["build/icon.png", "build/installerIcon.ico"]);
  return root;
}

afterEach(() => {
  for (const root of roots.splice(0)) {
    // Removing a directory git has just written raises a transient EPERM on
    // Windows — measured as intermittent for the same tree shape, so it is a
    // handle the OS has not released yet rather than anything the test left
    // open. Retry, then give up: a temporary directory that outlives the run
    // is litter, not a failed assertion, and failing here would report the
    // guard as broken when it is not.
    try {
      rmSync(root, { recursive: true, force: true, maxRetries: 20, retryDelay: 50 });
    } catch {
      // Intentionally ignored; see above.
    }
  }
});

describe("check-generated-assets", () => {
  it("passes when the committed asset equals the generator's output", () => {
    const root = createRepo();

    const result = run(root);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("[generated-assets] OK");
  });

  it("fails and names the asset when the generated bytes diverge from the commit", () => {
    const root = createRepo();
    write(root, "build/installerIcon.ico", "regenerated-bytes");

    const result = run(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("build/installerIcon.ico");
    expect(result.stderr).toContain("committed bytes differ from generator output");
    expect(result.stderr).toContain("[generated-assets] FAIL — 1 tracked generated asset(s)");
  });

  it("still fails once the divergent bytes are staged", () => {
    const root = createRepo();
    write(root, "build/installerIcon.ico", "regenerated-bytes");
    git(root, ["add", "build/installerIcon.ico"]);

    const result = run(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("build/installerIcon.ico");
  });

  it("accepts an asset re-encoded by a different deflate, pixels unchanged", () => {
    // Not a hypothetical: `deflate` output depends on the zlib the generator's
    // runtime was linked against, so two Windows checkouts on different Node
    // versions produce different bytes for the same icon. Committing the
    // regenerated bytes — what the failure message suggests — only moves the
    // failure to the next machine.
    const root = createRepo();
    commitIco(root, "build/installerIcon.ico", icoWith(PIXELS, 9));
    writeBytes(root, "build/installerIcon.ico", icoWith(PIXELS, 1));

    const result = run(root);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("different deflate encoding; not a divergence");
    expect(result.stdout).toContain("[generated-assets] OK");
  });

  it("still fails when the re-encoded asset draws something else", () => {
    const root = createRepo();
    commitIco(root, "build/installerIcon.ico", icoWith(PIXELS, 9));
    writeBytes(root, "build/installerIcon.ico", icoWith(OTHER_PIXELS, 1));

    const result = run(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("committed bytes differ from generator output");
  });

  it("ignores generated outputs that are not tracked", () => {
    const root = createRepo();
    write(root, "build/icon.png", "anything at all");

    const result = run(root);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("[generated-assets] OK");
  });

  it("fails when the generator has not recorded a manifest", () => {
    const root = createRepo();
    rmSync(join(root, MANIFEST));

    const result = run(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("bun run build:icons");
  });

  it("fails when the manifest is not a list of paths", () => {
    const root = createRepo();
    write(root, MANIFEST, `${JSON.stringify({ "build/icon.png": true })}\n`);

    const result = run(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("is not a list of paths");
  });

  it("reports on --root even when git names another repository in the environment", () => {
    // The guard runs inside `bun run build`, which the pre-push hook invokes,
    // and git exports GIT_DIR to its hooks. GIT_DIR outranks `-C`, so without
    // this the guard would answer for whichever repository git was pushing.
    // The fixture is left CLEAN, and the assertion is that the guard agrees.
    // Asserting a failure would not discriminate: a guard reading this
    // repository's HEAD would also report the fixture's bytes as divergent, and
    // pass for the wrong reason. Only a guard actually rooted at `--root` can
    // call this tree clean.
    const root = createRepo();
    // Resolved, not `REPO_ROOT/.git`: inside a worktree that path is a pointer
    // file which git ignores, and an inert value proves nothing.
    const gitDir = spawnSync("git", ["-C", REPO_ROOT, "rev-parse", "--absolute-git-dir"], {
      encoding: "utf-8",
      env: forcedEnv(AMBIENT_GIT_VARS),
    }).stdout.trim();
    expect(gitDir).not.toBe("");

    // Keep the force flag: this case is about GIT_DIR overriding `--root`, and
    // a platform skip would let it pass without ever reaching that question.
    const result = run(root, {
      ...process.env,
      GIT_DIR: gitDir,
      LVIS_GENERATED_ASSETS_FORCE: "1",
    });

    expect(result.stderr).toBe("");
    expect(result.status).toBe(0);
    expect(result.stdout).toContain("[generated-assets] OK");
  });

  it("skips where there is no committed state to compare against", () => {
    const root = mkdtempSync(join(tmpdir(), "lvis-generated-assets-bare-"));
    roots.push(root);
    writeManifest(root, ["build/installerIcon.ico"]);

    const result = run(root);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("[generated-assets] SKIP");
  });
});

describe("generated-asset manifest", () => {
  // `test:prepare` runs `bun run build:icons`, so the manifest and the assets
  // it names are present whenever the suite runs.
  it("records every asset the generator wrote", () => {
    const manifest: string[] = JSON.parse(readFileSync(join(REPO_ROOT, MANIFEST), "utf-8"));

    expect(manifest.length).toBeGreaterThan(0);
    for (const rel of manifest) {
      expect(existsSync(join(REPO_ROOT, rel)), `${rel} is listed but was not written`).toBe(true);
    }
  });

  it("covers the tracked branding assets the installer reads from the tree", () => {
    const manifest: string[] = JSON.parse(readFileSync(join(REPO_ROOT, MANIFEST), "utf-8"));

    // A tracked generated file missing from the manifest is invisible to the
    // guard, which is the whole failure mode — so assert the coverage rather
    // than trusting that every write goes through `emit`.
    expect(manifest).toContain("build/installerIcon.ico");
    expect(manifest).toContain("build/installerHeaderIcon.ico");
    expect(manifest).toContain("build/icon.svg");
  });

  it("runs the guard in the build, after the generator that feeds it", () => {
    // Without this the guard is a script nobody calls: every assertion above
    // would still pass while the drift it exists to catch went unnoticed.
    const build: string = JSON.parse(
      readFileSync(join(REPO_ROOT, "package.json"), "utf-8"),
    ).scripts.build;

    const generate = build.indexOf("bun run build:icons");
    const check = build.indexOf("node scripts/check-generated-assets.mjs");

    expect(generate).toBeGreaterThanOrEqual(0);
    expect(check).toBeGreaterThan(generate);
  });

  it("leaves the repository's own tracked assets matching the generator", () => {
    // The #1974 regression itself: run the real guard against the real
    // checkout. It goes red the moment a committed blob and the generator
    // disagree again.
    //
    // Unforced, unlike every case above: the committed blobs here were written
    // by the win32 encoder, so on darwin/linux this asks a question the tree
    // cannot answer and the guard's platform skip is the correct outcome. On
    // Windows — where the installer icons are actually consumed — the
    // comparison runs for real, which is where the regression would surface.
    const result = run(REPO_ROOT, envWithout(AMBIENT_GIT_VARS));

    expect(result.stderr).toBe("");
    expect(result.status).toBe(0);
  });
});
