import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

const REPO_ROOT = process.cwd();
const SCRIPT = resolve(REPO_ROOT, "scripts/check-generated-assets.mjs");
const MANIFEST = "build/generated-assets.json";
const nodeCommand = process.env.LVIS_TEST_NODE_EXEC_PATH ?? process.execPath;
const roots: string[] = [];

function run(root: string) {
  return spawnSync(nodeCommand, [SCRIPT, "--root", root], {
    cwd: REPO_ROOT,
    encoding: "utf-8",
  });
}

function git(root: string, args: string[]) {
  const result = spawnSync(
    "git",
    [
      "-C",
      root,
      "-c",
      "user.email=guard@test.invalid",
      "-c",
      "user.name=guard",
      "-c",
      "commit.gpgsign=false",
      ...args,
    ],
    { encoding: "utf-8" },
  );
  if (result.status !== 0) {
    throw new Error(`git ${args.join(" ")} failed: ${result.stderr}`);
  }
  return result;
}

function write(root: string, rel: string, contents: string): void {
  const path = join(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, "utf-8");
}

function writeManifest(root: string, paths: string[]): void {
  write(root, MANIFEST, `${JSON.stringify(paths, null, 2)}\n`);
}

/**
 * A throwaway repository holding one tracked generated asset committed with
 * the bytes the generator is pretending to have produced, so a later rewrite
 * of that file is exactly the divergence the guard exists to catch.
 */
function createRepo(): string {
  const root = mkdtempSync(join(tmpdir(), "lvis-generated-assets-"));
  roots.push(root);
  git(root, ["init", "--quiet"]);
  write(root, ".gitignore", "build/generated-assets.json\nbuild/icon.png\n");
  write(root, "build/installerIcon.ico", "committed-bytes");
  git(root, ["add", ".gitignore", "build/installerIcon.ico"]);
  git(root, ["commit", "--quiet", "-m", "seed"]);
  writeManifest(root, ["build/icon.png", "build/installerIcon.ico"]);
  return root;
}

afterEach(() => {
  for (const root of roots.splice(0)) {
    // Removing a directory git has just written raises a transient EPERM on
    // Windows — measured as intermittent for the same tree shape, so it is a
    // handle the OS has not released yet rather than anything the test left
    // open. Retry, then give up: a temporary directory that outlives the run
    // is litter, not a failed assertion, and failing here would report the
    // guard as broken when it is not.
    try {
      rmSync(root, { recursive: true, force: true, maxRetries: 20, retryDelay: 50 });
    } catch {
      // Intentionally ignored; see above.
    }
  }
});

describe("check-generated-assets", () => {
  it("passes when the committed asset equals the generator's output", () => {
    const root = createRepo();

    const result = run(root);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("[generated-assets] OK");
  });

  it("fails and names the asset when the generated bytes diverge from the commit", () => {
    const root = createRepo();
    write(root, "build/installerIcon.ico", "regenerated-bytes");

    const result = run(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("build/installerIcon.ico");
    expect(result.stderr).toContain("committed bytes differ from generator output");
    expect(result.stderr).toContain("[generated-assets] FAIL — 1 tracked generated asset(s)");
  });

  it("still fails once the divergent bytes are staged", () => {
    const root = createRepo();
    write(root, "build/installerIcon.ico", "regenerated-bytes");
    git(root, ["add", "build/installerIcon.ico"]);

    const result = run(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("build/installerIcon.ico");
  });

  it("ignores generated outputs that are not tracked", () => {
    const root = createRepo();
    write(root, "build/icon.png", "anything at all");

    const result = run(root);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("[generated-assets] OK");
  });

  it("fails when the generator has not recorded a manifest", () => {
    const root = createRepo();
    rmSync(join(root, MANIFEST));

    const result = run(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("bun run build:icons");
  });

  it("fails when the manifest is not a list of paths", () => {
    const root = createRepo();
    write(root, MANIFEST, `${JSON.stringify({ "build/icon.png": true })}\n`);

    const result = run(root);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("is not a list of paths");
  });

  it("skips where there is no committed state to compare against", () => {
    const root = mkdtempSync(join(tmpdir(), "lvis-generated-assets-bare-"));
    roots.push(root);
    writeManifest(root, ["build/installerIcon.ico"]);

    const result = run(root);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("[generated-assets] SKIP");
  });
});

describe("generated-asset manifest", () => {
  // `test:prepare` runs `bun run build:icons`, so the manifest and the assets
  // it names are present whenever the suite runs.
  it("records every asset the generator wrote", () => {
    const manifest: string[] = JSON.parse(readFileSync(join(REPO_ROOT, MANIFEST), "utf-8"));

    expect(manifest.length).toBeGreaterThan(0);
    for (const rel of manifest) {
      expect(existsSync(join(REPO_ROOT, rel)), `${rel} is listed but was not written`).toBe(true);
    }
  });

  it("covers the tracked branding assets the installer reads from the tree", () => {
    const manifest: string[] = JSON.parse(readFileSync(join(REPO_ROOT, MANIFEST), "utf-8"));

    // A tracked generated file missing from the manifest is invisible to the
    // guard, which is the whole failure mode — so assert the coverage rather
    // than trusting that every write goes through `emit`.
    expect(manifest).toContain("build/installerIcon.ico");
    expect(manifest).toContain("build/installerHeaderIcon.ico");
    expect(manifest).toContain("build/icon.svg");
  });

  it("runs the guard in the build, after the generator that feeds it", () => {
    // Without this the guard is a script nobody calls: every assertion above
    // would still pass while the drift it exists to catch went unnoticed.
    const build: string = JSON.parse(
      readFileSync(join(REPO_ROOT, "package.json"), "utf-8"),
    ).scripts.build;

    const generate = build.indexOf("bun run build:icons");
    const check = build.indexOf("node scripts/check-generated-assets.mjs");

    expect(generate).toBeGreaterThanOrEqual(0);
    expect(check).toBeGreaterThan(generate);
  });

  it("leaves the repository's own tracked assets matching the generator", () => {
    // The #1974 regression itself: run the real guard against the real
    // checkout. It goes red the moment a committed blob and the generator
    // disagree again.
    const result = run(REPO_ROOT);

    expect(result.stderr).toBe("");
    expect(result.status).toBe(0);
  });
});
