/**
 * useChatState — suggested-replies lifetime across transcript changes.
 *
 * Suggested replies live in a renderer singleton that deliberately outlives
 * view remounts, so nothing about a component unmount bounds them. The
 * transcript intents are what mark the end of the conversation they describe:
 * every intent that replaces or rewinds the transcript must drop them, or the
 * next (possibly empty) conversation inherits a snapshot that still reads as
 * "suggestions on screen" — which is what suppresses the empty-state centered
 * composer and its project selector.
 */
import "../../../../../test/renderer/setup.js";
import { describe, it, expect, beforeEach } from "vitest";
import { act, renderHook } from "@testing-library/react";
import { useChatState } from "../use-chat-state.js";
import {
  useSuggestedReplies,
  pushSuggestedReply,
  dismissSuggestedReplies,
  __resetSuggestedRepliesStoreForTests,
  __teardownSuggestedRepliesIpcForTests,
} from "../use-suggested-replies.js";
import type { LvisApi } from "../../types.js";
import type { ChatEntry } from "../../../../lib/chat-stream-state.js";
import { makeMockLvisApi } from "../../../../../test/renderer/mock-lvis-api.js";

function setup() {
  const { api } = makeMockLvisApi();
  const chat = renderHook(() => useChatState(api as unknown as LvisApi));
  const replies = renderHook(() => useSuggestedReplies());
  act(() => {
    pushSuggestedReply("다음 작업 진행");
  });
  expect(replies.result.current.text).toBe("다음 작업 진행");
  return { chat, replies };
}

const TURN: ChatEntry[] = [
  { kind: "user", text: "질문" },
  { kind: "assistant", text: "답변" },
];

describe("useChatState — suggested replies are scoped to the transcript on screen", () => {
  beforeEach(() => {
    __resetSuggestedRepliesStoreForTests();
    __teardownSuggestedRepliesIpcForTests();
  });

  it("clearForNewChat drops the previous conversation's suggestions", () => {
    const { chat, replies } = setup();

    act(() => chat.result.current.clearForNewChat());

    expect(chat.result.current.entries).toEqual([]);
    expect(replies.result.current).toEqual({ text: null, isDismissed: false });
  });

  it("applyLoadedSession drops suggestions the loaded session did not produce", () => {
    const { chat, replies } = setup();

    act(() => chat.result.current.applyLoadedSession(TURN));

    expect(chat.result.current.entries).toHaveLength(2);
    expect(replies.result.current.text).toBeNull();
  });

  it("seedRoutineEntries drops suggestions from the conversation it replaces", () => {
    const { chat, replies } = setup();

    act(() => chat.result.current.seedRoutineEntries(TURN));

    expect(replies.result.current.text).toBeNull();
  });

  it("truncateToEntry drops suggestions generated by the rewound turn", () => {
    const { chat, replies } = setup();
    act(() => chat.result.current.applyLoadedSession(TURN));
    act(() => {
      pushSuggestedReply("이어서 진행");
    });
    expect(replies.result.current.text).toBe("이어서 진행");

    act(() => chat.result.current.truncateToEntry(0));

    expect(chat.result.current.entries).toHaveLength(1);
    expect(replies.result.current.text).toBeNull();
  });

  it("a dismissed snapshot does not leave the latch set for the next conversation", () => {
    const { chat, replies } = setup();
    act(() => dismissSuggestedReplies());

    act(() => chat.result.current.clearForNewChat());
    act(() => {
      pushSuggestedReply("새 대화의 첫 제안");
    });

    expect(replies.result.current.text).toBe("새 대화의 첫 제안");
    expect(replies.result.current.isDismissed).toBe(false);
  });
});
