/**
 * Unit tests for demo-activation-codec.ts — AES-GCM encrypt/decrypt
 * round-trip + tamper detection + parser correctness.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  ACTIVATION_PREFIX,
  encryptActivationPayload,
  decryptActivationCode,
  parseEnvDemoText,
} from "../demo-activation-codec.js";
import {
  loadPersistedDemoActivationSync,
  persistedEnvDemoPath,
} from "../demo-activation-loader.js";
import { mkdtempSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";

const SAMPLE_ENV = [
  "# .env.demo — generated by encrypt-demo-credentials.mjs",
  "LVIS_DEMO_VENDOR=azure-foundry",
  "LVIS_DEMO_KEY_AZURE_FOUNDRY=sk-test-key-123",
  "LVIS_DEMO_BASEURL_AZURE_FOUNDRY=https://aif-swc-axpg-hq-hckt19.openai.azure.com/openai/v1/",
  "LVIS_DEMO_MODEL_AZURE_FOUNDRY=gpt-4o",
  "",
].join("\n");

describe("encryptActivationPayload / decryptActivationCode", () => {
  it("round-trips a typical .env.demo payload", () => {
    const code = encryptActivationPayload(SAMPLE_ENV);
    expect(code.startsWith(ACTIVATION_PREFIX)).toBe(true);
    expect(code).not.toContain("sk-test-key-123"); // payload not plaintext
    const decoded = decryptActivationCode(code);
    expect(decoded).toBe(SAMPLE_ENV);
  });

  it("produces a different ciphertext per call (random IV)", () => {
    const a = encryptActivationPayload(SAMPLE_ENV);
    const b = encryptActivationPayload(SAMPLE_ENV);
    expect(a).not.toBe(b);
    // Both still decrypt to the same plaintext.
    expect(decryptActivationCode(a)).toBe(SAMPLE_ENV);
    expect(decryptActivationCode(b)).toBe(SAMPLE_ENV);
  });

  it("tolerates surrounding whitespace from clipboard paste", () => {
    const code = encryptActivationPayload(SAMPLE_ENV);
    expect(decryptActivationCode(`  ${code}\n`)).toBe(SAMPLE_ENV);
  });

  it("rejects an empty string", () => {
    expect(() => decryptActivationCode("")).toThrow();
  });

  it("rejects a non-string", () => {
    // @ts-expect-error — intentionally testing runtime guard
    expect(() => decryptActivationCode(null)).toThrow();
  });

  it("rejects a missing prefix", () => {
    expect(() => decryptActivationCode("not-a-valid-code")).toThrow(
      /prefix/i,
    );
  });

  it("rejects an empty payload after the prefix", () => {
    expect(() => decryptActivationCode(ACTIVATION_PREFIX)).toThrow(
      /empty/i,
    );
  });

  it("rejects a truncated payload (too short to contain iv+tag)", () => {
    expect(() => decryptActivationCode(`${ACTIVATION_PREFIX}abc`)).toThrow();
  });

  it("rejects a tampered ciphertext (GCM auth tag mismatch)", () => {
    const code = encryptActivationPayload(SAMPLE_ENV);
    // Flip a character inside the base64url payload — should fail
    // authentication tag verification on decrypt.
    const idx = code.length - 5;
    const tampered =
      code.slice(0, idx) + (code[idx] === "a" ? "b" : "a") + code.slice(idx + 1);
    expect(() => decryptActivationCode(tampered)).toThrow();
  });

  it("rejects corrupt base64", () => {
    expect(() =>
      decryptActivationCode(`${ACTIVATION_PREFIX}!!!not-base64!!!`),
    ).toThrow();
  });

  it("rejects an empty plaintext on encrypt", () => {
    expect(() => encryptActivationPayload("")).toThrow();
  });
});

describe("parseEnvDemoText", () => {
  it("parses KEY=VALUE lines", () => {
    const out = parseEnvDemoText("FOO=bar\nBAZ=qux\n");
    expect(out).toEqual({ FOO: "bar", BAZ: "qux" });
  });

  it("skips comments and blank lines", () => {
    const out = parseEnvDemoText("# hello\n\nFOO=bar\n# end\n");
    expect(out).toEqual({ FOO: "bar" });
  });

  it("strips leading `export ` prefix", () => {
    const out = parseEnvDemoText("export FOO=bar\n");
    expect(out).toEqual({ FOO: "bar" });
  });

  it("strips surrounding double and single quotes", () => {
    const out = parseEnvDemoText('FOO="bar"\nBAZ=\'qux\'\n');
    expect(out).toEqual({ FOO: "bar", BAZ: "qux" });
  });

  it("preserves empty values (intentional clear)", () => {
    const out = parseEnvDemoText("LVIS_DEMO_HOST_MAP=\n");
    expect(out).toEqual({ LVIS_DEMO_HOST_MAP: "" });
  });

  it("ignores lines without `=`", () => {
    const out = parseEnvDemoText("no-equals-here\nFOO=bar\n");
    expect(out).toEqual({ FOO: "bar" });
  });

  it("handles CRLF line endings", () => {
    const out = parseEnvDemoText("FOO=bar\r\nBAZ=qux\r\n");
    expect(out).toEqual({ FOO: "bar", BAZ: "qux" });
  });
});

describe("loadPersistedDemoActivationSync", () => {
  let tempHome: string;
  const ORIGINAL_ENV = { ...process.env };
  const ORIGINAL_LVIS_HOME = process.env.LVIS_HOME;

  beforeEach(() => {
    tempHome = mkdtempSync(join(tmpdir(), "lvis-demo-codec-test-"));
    process.env.LVIS_HOME = tempHome;
    // Wipe demo env so we observe what the loader injects.
    for (const k of Object.keys(process.env)) {
      if (k.startsWith("LVIS_DEMO_")) delete process.env[k];
    }
  });

  afterEach(() => {
    rmSync(tempHome, { recursive: true, force: true });
    process.env = { ...ORIGINAL_ENV };
    if (ORIGINAL_LVIS_HOME === undefined) {
      delete process.env.LVIS_HOME;
    } else {
      process.env.LVIS_HOME = ORIGINAL_LVIS_HOME;
    }
  });

  it("returns empty when no persisted file exists", () => {
    const out = loadPersistedDemoActivationSync();
    expect(out).toEqual({});
  });

  it("loads and injects a persisted .env.demo file", () => {
    const path = persistedEnvDemoPath();
    mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
    writeFileSync(path, SAMPLE_ENV, { mode: 0o600 });

    const out = loadPersistedDemoActivationSync();
    expect(out.LVIS_DEMO_VENDOR).toBe("azure-foundry");
    expect(out.LVIS_DEMO_KEY_AZURE_FOUNDRY).toBe("sk-test-key-123");
    expect(process.env.LVIS_DEMO_VENDOR).toBe("azure-foundry");
    expect(process.env.LVIS_DEMO_KEY_AZURE_FOUNDRY).toBe("sk-test-key-123");
  });

  it("does not overwrite an existing process.env value (shell precedence)", () => {
    const path = persistedEnvDemoPath();
    mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
    writeFileSync(path, "LVIS_DEMO_VENDOR=azure-foundry\n", { mode: 0o600 });
    process.env.LVIS_DEMO_VENDOR = "openai"; // shell-set override

    loadPersistedDemoActivationSync();
    expect(process.env.LVIS_DEMO_VENDOR).toBe("openai");
  });
});
